### ISSUE TITLE
Add initial validation and diagnostics for input collection

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#1]
Before we initiate the search, we need to make sure that we can create all of the necessary products from the source collection. So that means the documents must, at minimum:

* Be parsable as XML
* Be in the XHTML namespace (http://www.w3.org/1999/xhtml)

If those two conditions aren't satisfied, then we fail immediately. 

But we also should have some diagnostics for the input that checks whether or not the documents have things that won't necessarily break the process, but may make the results sub-optimal. This will include things like:

* Documents without a declared `@lang` on the root `<html>` element
* Documents that do not have declared metadata in the header that we expect

**Comment by joeytakeda** [comment]
We now have the XHTML collection be validated using the `<xmlvalidate>` task in ANT. We're also validating the config file, but not failing.

Diagnostics stuff is mostly in the report; documents without `@lang` are already flagged, but we need to do the metadata still.

**Comment by martindholmes** [comment]
I did add info to the report on search filters found, so I think this is now done.
