### ISSUE TITLE
Integrate with Travis

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#10]
To help with development, we should integrate this repository with Travis and deploy the results in a separate repository that's dedicated to serving the results of the test documents both against the dev branch and the master branch.

This will involve creating a new repository and another build process that simply runs the static search build and updates the index page; we'll also have to configure the build such that it knows what branch it's working with at the moment.

**Comment by martindholmes** [comment]
We also need a test set that's very small but covers all the bases; that's a bit tricky to build. The current test set was focused largely on the tokenizing process; perhaps we should replace it with a hand-crafted set of (say) ten documents which include multiple configurations of the filter types.

**Comment by joeytakeda** [comment]
Yes, I agree that our test set needs to be as comprehensive as possible to detect any errors, et cetera. Just to think about all things we need to test:

* Nested documents
* Documents without ids
* Documents with different `@xml:lang` from the root (which means something other than English currently)
* Documents with duplicate titles
* Documents with duplicate ids
* Documents with `<span>` tags and a variety of XHTML5 elements
* Hyphenated phrases
* Filters
    * Boolean filters
    * Multiple string filters
    * Date filters

So it depends on whether we just need to fix the current test set and add filters across them, or whether we should do something a bit more elegant. We could grab documents from each of the projects and use those; or we could maybe use our own documentation for this, but things like date filters wouldn't really apply to the documentation. What do you think?

**Comment by martindholmes** [comment]
Given that the current test set covers most of the first few requirements, I would say that we could just add filters to those documents, along with a bit more text so that the text search can be more sophisticated. A few paras from different sources would be good, spread across the collection.

**Comment by joeytakeda** [comment]
Travis is now integrated in both the /dev/ and /master/ branches. It's all quite rudimentary still, but the bones are there.

**Comment by joeytakeda** [comment]
Perhaps spoken too soon.....It seems that the deployment in Travis overwrites the /dev/ branch with the /master/ (i.e. moving the files) even with the keep-history flag is set to true. Need to do some digging here...

**Comment by joeytakeda** [comment]
We’ve decided to remove Travis integration in favor of Jenkins, so closing this.
