### ISSUE TITLE
No more Nashorn in Java: need an alternative way of opening web pages

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#103]
Our current build process generates a nice report (in future it will be several -- see FR #27), and currently we use JS embedded in the Ant build file to open it in a browser. The JS engine Nashorn has finally been removed from OpenJDK, and the first version where this happens has landed in the Oxygen distribution, so this approach is no longer workable. Options:
1. Don't open the file at all; just tell people where it is. (When there are multiple files this may make sense anyway, unless there is a single index file that links to them.)
2. Experiment with and settle on a platform-sensitive approach which uses the exec element to open files. This could be linked with issue #33, which is also a platform problem.
3. Something else?

**Comment by joeytakeda** [comment]
I personally think 1—just don’t open it. The report is interesting and should be looked at, but in most cases the build is either going to be run in a CI or run a number of times in quick succession at the command line to test/debug things.

**Comment by martindholmes** [comment]
Agreed. That means we can do this for 1.1. I'll grab it now.

**Comment by martindholmes** [comment]
Done.
