### ISSUE TITLE
Add "What's New" section to documentation and update for 1.1

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#106]
We need a section in the documentation where we accumulate explanations of changes since 1.0. It should be included in the 1.1 release.

**Comment by joeytakeda** [comment]
Should we just point to the release notes? Or, going the other way, should our release notes point to our documentation?

**Comment by martindholmes** [comment]
What release notes?

**Comment by joeytakeda** [comment]
But in the past we have given some fairly detailed outline of changes in the release notes: https://github.com/projectEndings/staticSearch/releases/tag/0.8 (some more so than others). So, I had presumed that part of the release would include a fairly detailed list, and that if we were to have the same set of information in two places, there's a chance that they could get out of sync and cause confusion.

So my questions are:

* Is there information that is meant to be in the documentation versus in the release notes? I.e. should all changes be listed in the release notes while the documentation only contains information about things people might care about (i.e. if a new configuration option is added, etc)? 
* If we think not, then should we have a single place for this information and then link to it? I.e. should the list of changes for a single release be in the Github release notes and the documentation simply points to that page (i.e. "The current version of static search is 1.1. To see all changes up to  1.1, see the release notes"), or should the release notes be briefer and point to the documentation section?

**Comment by martindholmes** [comment]
I think we should have a section in the documentation for changes following the 1.0 release, in sections for each subsequent release; the info should travel with the package, rather than (or as well as) being on GitHub. We should probably copy/paste that section into the release message on GitHub, though.

**Comment by martindholmes** [comment]
@joeytakeda I'll work on this today and tomorrow, and we'll see if we can get a release done by the end of the week.

**Comment by martindholmes** [comment]
@joeytakeda This is done now; take a look and see what you think, in case I've missed something. Also, I added two new projects which have just gone live with staticSearch to the list of projects.

**Comment by martindholmes** [comment]
I've updated the EDITION file to 1.1beta; when we're good to go, we should switch it to 1.1, build, release, then push it to 1.2alpha.

**Comment by joeytakeda** [comment]
This looks good to me! Thanks for doing that--unless you can think of anything else, I think 1.1 should be good to go.
