### ISSUE TITLE
Footnotes appearing on every page of the documentation

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#108]
I know @martindholmes noticed this before, but I completely forgot to fix this when we first split the documentation into separate files. The footnote to Thomas Kuhn is appears on every page, but it should obviously only appear on the actual page.

**Comment by martindholmes** [comment]
Made this a release-blocker because it's a visible bug.

**Comment by martindholmes** [comment]
Working on this in issue-108-footnotes branch.

**Comment by martindholmes** [comment]
Done and dusted.
