### ISSUE TITLE
Robust querystring handling required

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#11]
It's essential that the entire set of controls on the search page can be configured from a search query string, so that users can bookmark searches and progress through them using browser history, as well as share them. This obviously includes the filters. Doing a search should change the browser URL (without a page reload, obviously), and loading a URL with a query string needs to configure the search controls and then run the search. The bones of the latter are already in place, in a function that just needs to be filled out.

**Comment by joeytakeda** [comment]
Just tried the results of commit https://github.com/projectEndings/staticSearch/commit/6d01a499a2a23c81581ff108e14f27fad850f0f7 and works perfectly in desktop Safari, Firefox, and Chrome.

**Comment by martindholmes** [comment]
I think this is fully tested and working, so I'll close it.
