### ISSUE TITLE
Determine how to render large result sets: pagination?

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#111]
In an email discussion, we started to talk about how to deal with rendering huge result sets: for most projects, this is never an issue, but for some large projects, doing a document only search can end up outputting tens of thousands of results, which can be painful to the browser to render etc. One idea is to prevent docOnly searches in some cases, but that doesn't address the full problem (since you could search for something that appears in 5000 documents in a 80,000 document collection). And we also discussed the idea of incrementally rendering results (i.e. appending 100 items, then appending the next 100, etc). But I think if we're starting to go down the path of needing to show a subsets of results, then we might as well just bite the bullet and add pagination. 

IMO, in most use cases of staticSearch, pagination would do more harm than good since the majority of projects have small result sets that render instantly and so paginating those results would mean simply hiding stuff that people might actually want to see (which is backed up by UX research: https://www.nngroup.com/articles/item-list-view-all/).  So one idea is setting the default `resultsPerPage` to something like `1000` so that the vast majority of time it's never triggered, but it would be for large collections. And once that logic is in place, then implementers could add their own page limit if they want a smaller subset of results. Of course, adding pagination also means adding a pagination widget in rendering and that as a parameter to the URL.

(I also note that we already have resultsPerPage in the JS:

https://github.com/projectEndings/staticSearch/blob/def60ed52a9773521157f8a9583f555cd74cc5c6/js/ssSearch.js#L360

We don't have a `<resultsPerPage>` in the config schema, though and, as the comment above it says, it doesn't actually do anything.)

**Comment by martindholmes** [comment]
I don't actually agree that we should do traditional pagination; I think we should /either/ incrementally and automatically add document sets by the 100, or 200, or whatever, to the page, so that the user can start to browse the first few quite quickly, but then the document keeps expanding every few seconds to give you the full set; /or/ we should provide a link at the bottom of the rendered result set to add the next lot (perhaps along with a Show All button). Actual pagination (where the old set of results disappears and is replaced by the new) is annoying for all the reasons we've talked about before -- you lose what you were looking at just a moment ago -- and its only real purpose is to reduce server load for server-side search engines. 

It's also worth remembering that search results are currently bookmarkable URLs in the browser history; if the same result set has multiple incarnations, we need to make sure that doesn't bork the history/back button behaviour.

**Comment by joeytakeda** [comment]
I think the Show More / Show All is totally the right solution: all of the results stay on the page but the page doesn't have to work as hard to render those items, especially if the search was just accidental (you meant to click another filter or add a term but clicked search instead).

For configuration options, either we could set a fairly high number (say 500 or something?) as the default resultsPerPage or we could just have it turned off completely unless the number is set.

In terms of implementation, you might already have a good plan for this, but one reason why I like the Show More / Show All is that it would work almost entirely with CSS: 

* When we create the search page, we add a CSS custom property that has the resultsPerPage parameter:

```
:root{
--ssResultsPerPage: 50
}

#ssResults > ul.paginated > li:nth-child(n + var(--ssResultsPerPage)){
display:none;
}

```

But also retain it in the staticSearch data-attribute `@data-ss-resultsPerPage` (or `results-per-page`, if we decide to switch those to hyphenated)

* If the number of results is greater than the limit, then add the paginated class to the `ul`, and add the Show More / Show All button (or, we always have the Show More / Show All button but hide them if the list isn't paginated)

* The Show More button could just increment the ssResultsPerPage variable by the configured limit (so, clicking Show More would increase --ssResultsPerPage to 100, then 150, etc).
*  The Show All would just remove the paginated class on the `ul`.

Of course, a Javascript solution would be a bit less kludgy, but I sort of like this since it's minimally intrusive in terms of the Javascript.

**Comment by martindholmes** [comment]
I really like that. The only question would be whether it's the construction and addition of the enormous DOM of result elements that hurts the browser, or the display of them. If the pain is in the display, then this will work perfectly, but if what takes the time is the DOM parsing, that will happen anyway before the CSS kicks in (I presume, at least). One way to test this would be to save a rendered page with a massive result set and see how long it takes the browser to render it with and without the CSS rule.

**Comment by joeytakeda** [comment]
Yes, we should definitely test this. From what I can tell from reading the CSS spec, `display: none` prevents the DOM from adding it to the "box tree," meaning that the browser knows it's not going to do anything with it at all and so it basically ignores it (https://www.w3.org/TR/css-display-3/#ref-for-valdef-display-none%E2%91%A3). But I'll give testing this a shot and report back.

**Comment by joeytakeda** [comment]
Just tested this and it looks like the CSS solution should work nicely. I generated 200,000 files from a data dump of Wikipedia's XML abstracts (so the pages themselves were trivially small) and added the same meta tag to all of them so that they would all be collected when that filter was checked. I also added an input button to switch the CSS on and off and tested after a hard refresh. 

Retrieving and displaying all 200,000 blocked the page for 3087ms with 56% (1902.2ms) of that time spent recalculating style (and 23.4% laying out).

![iss111-showAllResults](https://user-images.githubusercontent.com/17664763/104532226-95cb1f00-55c4-11eb-9a47-133aa25b17ab.png)



Retrieving all 200,000 but only showing 50 of them blocked the 441.23ms with 24.7% (152ms) of that time spent recalculating style (and only 0.3% of that time spent laying out).

![iss111-show50Results](https://user-images.githubusercontent.com/17664763/104532232-98c60f80-55c4-11eb-9240-9008b566732b.png)

So I think the CSS only approach should work quite nicely--we'll need to see on an actual project with complicated CSS, but this suggests to me that it should work.

**Comment by martindholmes** [comment]
Nice experiment! It's always good to have solid evidence for the thing that you want to be true. :-)

**Comment by joeytakeda** [comment]
(Thanks! I also learned that you can save the profiles and re-load them in Chrome, which is a handy feature (though there's no web-based comparison thing, which is what I really wanted but oh well))

So just to lay out the implementation details:

* Add `<resultsPerPage>` to the schema (with documentation): How should that work? Should it be that resultsPerPage is set to a high number by default (say 500 or something) or should omitting `<resultsPerPage>` mean that you never want pagination no matter how many results there might be? 
* Add the special CSS custom property (possibly depending on if resultsPerPage is set) to the search page
* Add the appropriate JS handling so that it knows to add that "Read More" and "Read all" button when results > resultsPerPage and that "Read More" should increment the custom property and Read All should just remove the paginated class altogether. 

Sound right to you?

**Comment by martindholmes** [comment]
I think when `<resultsPerPage>` is missing OR is set to zero, you don't get pagination.
I think we want "Show all" and "Show more", no?
I'll also have to get those captions from Claire in French.
Should we also modify the documents-found count at the top of the result set to show e.g. "Documents found: 200 / 350"?

**Comment by joeytakeda** [comment]
* Sounds good to me. 
* Yes, the buttons should definitely be captions and they should by default by Show all and Show more in English
* That seems like a good idea--it is slightly misleading though, since that could be read as "Found 250 documents out of a possible 350." What about "Documents found: 350. Showing 200" (or, "Showing 200 documents of 350 found")?

**Comment by martindholmes** [comment]
The problem with captions which incorporate the numbers inside them is that they will be organized differently in other languages. "Showing 200 documents of 350 found" incorporates three pieces of text in English, but in another language there might be only two, in a different order relative to the numbers.
On reflection, I don't think we need to change the readout at the top; "Documents found: 350" is still true, and you only care about the pagination if/when you scroll down to the bottom of the current final page, at which point you'll see the buttons.

**Comment by joeytakeda** [comment]
Agreed—let’s not mess with the caption. 

I’ve assigned this to me, since it’s LOI that needs this.

**Comment by martindholmes** [comment]
I've added the relevant captions (ss.captions['en' | 'fr'].strShowMore, strShowAll) in dev. Let me know if there's anything else I can do.

**Comment by joeytakeda** [comment]
Thanks! I was waiting to start this so not to end up with merge issues with the new ssMark stuff, but that looks to be finished, so I’ll work on this today

**Comment by joeytakeda** [comment]
I've taken a stab at this now; it seems to work well (testing with the test set and the emod set), but the real test will be LOI.

I had to depart from my cunning plan to use CSS custom properties, since I incorrectly thought you could use custom properties in selectors--you can't, so something like `li:nth-child(var(--ssResultsPerPage) + n)` just won't work. 

So I've had to pivot the approach, but I used the same underlying idea:

* If the number of results exceeds the configured resultsPerPage limit, then create the Show More/ Show All button and add  the `ssPaginationEnd` class to the last item that should be shown (i.e. the 25th item if the page limit is 25). The CSS has a corresponding rule: `div#ssResults > ul > li.ssPaginationEnd ~ li{ display: none }`
* Clicking the Show More button removes that class from the last item and adds it to the next multiple
* Clicking the Show All buttons remove the class and hides the button div
* When you're on the last page, the Show More button does the same thing as the Show All button, removing the `ssPaginationEnd` class from the last item and hides the button div.

**Comment by joeytakeda** [comment]
Following @martindholmes ' comment here: https://github.com/projectEndings/staticSearch/commit/8b8618faa406f40ec19afabba053dc5670b53c83#commitcomment-46610628 , I've added a few more refinements:

* Everything that ought to be initialized in the constructor is
* I've also changed the logic slightly such that `paginateResults()` is only called when it needs to be (rather than that logic happening in the method itself)
* I've also made it so all of the methods return a boolean value, and wrapped everything in a try/catch switches to keep everything consistent.

I've kicked off the LOI build again, so will give that shot. Nice thing is that there we have 9 different search engines, but I've only configured the main one to use pagination at the moment, so it gives a good test. I'll also add switch WEA to this branch (but with no configured pagination) to make sure nothing is broken.

**Comment by martindholmes** [comment]
This looks good to me -- let me know when you've checked out LOI, and point me at the engine that uses it so I can see how it works. I'll probably put it into DVPP too.

**Comment by martindholmes** [comment]
I see it's the main generic search -- looks good, works perfectly. Happy to merge when you give me the word.

**Comment by joeytakeda** [comment]
Perfect! Pull request anon.

**Comment by joeytakeda** [comment]
Pull request now sent—once that's merged, I'll add in the documentation (both better documentation in the schemaSpec itself and an explanation in the configuration bit in the prose).

**Comment by martindholmes** [comment]
Now merged -- thanks! 

I've been progressively expanding the documentation in the elementSpecs whenever I get a minute, with an eye on eventually generating a config-building interface web page as we've previously discussed.

**Comment by martindholmes** [comment]
I think this was waiting on some documentation, but that appears to have been done as part of the wider push to generate prose documentation from remarks in the spec elements, so I'm going to close this.
