### ISSUE TITLE
Captions not properly documented, and French captions not available

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#112]
Right now, the JavaScript has only one set of captions/messages, in English. They're configured so that adding new languages is not difficult, and I'm going to be adding the French ones as soon as I have them back from Claire, but we also need to:

1. Make the JS fail gracefully and default to English where it has no captions for the language of the page; and
2. Document how to add your own captions for your own language, and how the JS determines the language for the captions.

Missing captions currently break the JS completely, so this is a release-blocker.

**Comment by joeytakeda** [comment]
Should the captions be accessible from outside of the JS? I.e. should we provide a mechanism for supplying captions outside of putting them in the JS (i.e. in an XML file or something) or is that overkill?

**Comment by martindholmes** [comment]
Problem number 1 should be fixed in dev now, but I still have to test it.

**Comment by martindholmes** [comment]
You can add captions externally after the JS object has been created by creating your own set and then assigning them to Sch.captionSet, but that's not ideal. Whatever we think the most elegant way to do it turns out to be, we need to document it clearly.

**Comment by martindholmes** [comment]
French captions have now landed in dev.

**Comment by martindholmes** [comment]
Added documentation in commit #8532a1b. Closing this.
