### ISSUE TITLE
Various linguistic issues with search page controls

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#113]
As I'm starting work on my first search page for a non-English project, I'm finding new issues related to language.

When we sort non-numeric filter checkboxes, we do it like this:

`<xsl:sort select="replace(map:string[@key='sortKey'], '^((the)|(a)|(an))\s+', '', 'i')"/>`

We need to add the `@lang` attribute from the root html element in the page (if there is one); and we also need to abstract the leading-article-replacement stuff so that we can supply better values for specific languages.

We also need to replace the hard-coded values in bool filter drop-downs with language-specific values or (probably better) Unicode check and cancel icons.

**Comment by martindholmes** [comment]
Options for check/cross marks (which will give us a chance to test browsers):

u+2611/u+2612:  ☑☒
u+2714/u+2718:  ✔✘

**Comment by joeytakeda** [comment]
Just to supplement @martindholmes above comment. here's what I see on macOS Mojave in

Chrome (88.0.4)

![Screen Shot 2021-01-19 at 5 51 29 PM](https://user-images.githubusercontent.com/17664763/105116239-31ee9d80-5a7f-11eb-89d9-dc96c009cfb2.png)

Safari (14.0.2)

![Screen Shot 2021-01-19 at 5 51 47 PM](https://user-images.githubusercontent.com/17664763/105116253-387d1500-5a7f-11eb-8bc1-8d8086da6655.png)

 u+2714/u+2718 is the winner on my system, it seems. Here they are in an a select: https://codepen.io/jtakeda/pen/ZEpPvBw

**Comment by martindholmes** [comment]
Interesting. They all work just fine for me in Linux. Shall we go for u+2714/u+2718: heavy_check_mark✘ then?

**Comment by martindholmes** [comment]
I've made this change in dev; let's see how it looks in the various projects.

**Comment by martindholmes** [comment]
Although more needs to be done on sorting here, I think this should no longer be a release-blocker, and I'm going to move it to 1.2.

**Comment by martindholmes** [comment]
Just to clarify: what remains to be addressed in this issue is the sort algorithm for non-numeric filter checkboxes. After some consideration, I think what we should do is to stress the fact that a sort key can be provided for these, and to add to the current English article list an equivalent set for a small number of common languages. That should be enough, I think.

**Comment by martindholmes** [comment]
I've added a quick fix for this in commit 47c8a77, and I think we can close it for now.
