### ISSUE TITLE
Fragment links should pass marked text as query-string parameter

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#114]
Given that Google's Scroll to Text Fragment proposal is not getting traction, it's likely that people are going to need to find a way to do hit-highlighting on target pages through JavaScript. Now that we have fragment pointers for our hits, it's more practical to provide a simple mechanism for this: where there is a kwic with a fragment pointer, we could simply add a query parameter containing the marked text from the kwic:

`targetpage.html?ssMark=escaped%20text#fragId`

We can provide example JS code for finding and highlighting the marked text, and implement it in those of our projects where it'll work reliably.

**Comment by martindholmes** [comment]
I now have a working implementation of this that I'm testing in the issue-114-ssMark branch, with the MyNDIR project. Once that's working, I'll try adding it to MoEML, so we can test with some longer pages.

**Comment by martindholmes** [comment]
Pull request in place for this. Documentation needs to be done in dev following the merge.

**Comment by joeytakeda** [comment]
This is now merged into the /dev/ branch.

**Comment by martindholmes** [comment]
There is of course a flaw in the rather crude example code: when you do a straight replace() on the innerHTML of an element, you can end up replacing stuff inside an attribute value or in a tag name. I'm working on an alternative approach in the despatches, where I have good examples of this problem; the result will almost certainly be slower, but it will probably be more robust.

**Comment by martindholmes** [comment]
I've implemented a safer approach to this which seems to be working in the Despatches; now going to port it to Mariage and MyNDIR for more robust testing.

**Comment by martindholmes** [comment]
This is complete and well-tested now.
