### ISSUE TITLE
docTitle, docSortKey, and docImage should allow for multiple classes

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#118]
The docTitle, docSortKey, and docImage retrieval functions all look for exact string equality:

https://github.com/projectEndings/staticSearch/blob/5a5189b871696f92ab6c650c534733150626f802/xsl/json.xsl#L1027

But since class could have multiple values, this should be a `contains-token()` rather than equals. I noticed this working on LOI where I'm want to specify a docTitle that prepends the document type to the document's title for the large site search only (it is isn't necessary for the document type specific searches, since it would just be redundant.)

I think this is a corrigible error, so I'm going to go and fix this in a branch for now.

**Comment by joeytakeda** [comment]
While I was working over in this branch https://github.com/projectEndings/staticSearch/tree/iss118-class-tokens, I realized that the docTitle, docSortKey, and docImage checks also weren't respecting `@data-staticSearch-exclude`, so I've added that in as well.

**Comment by martindholmes** [comment]
I guess the use-case here would be perhaps that you have two different docTitles, one excluded from one search and one excluded from the other; is that right? Otherwise I can't see why you would want multiples. And why would you use `@class` to do this? Why not use another data- element?

**Comment by joeytakeda** [comment]
Yes, that's exactly the case. In LOI, the global site search prepends the collection to the document's title to help disambiguate similarly named items; the individual collection searches don't need the collection prepended since they would just be redundant.

`@class` by definition contains a set of space-separated tokens so our processing should be able to handle that, which it already does for the rest of the staticSearch specific classes (`ssDesc` etc); docTitle, docSortKey, and docImage are the only instances where a `@class` must be an exact value. I see no harm in this: we don't have to recommend people use multiple class values, of course, but it just means our processing aligns with how people expect processors to handle `@class`.

**Comment by joeytakeda** [comment]
@martindholmes I've just done a PR and requested a review for this. Since I was working on the doc.+ metas anyway, I added a few small checks to tokenize.xsl to warning if a doc meta has a class/name mismatch (which is part of #73 but doesn't fix it entirely).

**Comment by martindholmes** [comment]
Looks good, now merged!
