### ISSUE TITLE
Add "Clear all inputs" button

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#12]
Small feature request for a button to clear all input fields to start with a fresh search. It would a fairly helpful thing both for testing and for the end-user who's trying multiple searches and simple to implement, as far as I can tell.

**Comment by martindholmes** [comment]
Absolutely. Where should it go?

**Comment by joeytakeda** [comment]
Ah I replied to this via email and it didn't go through--odd.

Anyway, I said:

I would say after the doSearch button. Our CSS can push it down to the next line so not to confuse visually the doSearch button with the Clear button, but others can move it wherever they want.

**Comment by joeytakeda** [comment]
I believe this is now done and merged into master--closing.
