### ISSUE TITLE
Set limit for handling large result sets

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#124]
As discussed over email, some searches in very large document collections --usually filter-only—can create result sets in the tens of thousands, which pose problems for the browsers' rendering engine when it constructs the DOM. 

@martindholmes suggests:

> Maybe it would be better to specify a result-limit, so that if the JS
> detects that the result set it larger than that limit, it doesn't try to
> render it at all, it just displays an error message. That would allow
> you to use filter-only searches, but just save the JS from having to
> build enormous doms, which I think is what's taking a lot of the time here.

This seems like the right approach to me, but there's a few questions to work through:

* What is the upper limit? I'd say something sufficiently high so that it's only triggered if it really needs to be. There's probably a good way to test this and come up with an actual figure, but, failing that, maybe something like 2000?

* Should the upper limit be configurable through the config? I'd be inclined to say no: in my mind, this is something that will only affect a small subset of projects—the limit is really just a stopgap to prevent ginormous collections from breaking things, so there's no reason that the majority of people would need to set this to something else.

**Comment by martindholmes** [comment]
I think this should be configurable, because the work of constructing the result dom depends entirely on the other options you have configured; if you have docImages, fragment images, and long kwics, it's a more complex task than if you have purely document title results, etc. A reasonable default would perhaps be 2000, but I would set it higher for some of my projects.

**Comment by joeytakeda** [comment]
Hi @martindholmes: I ran into some more issues with LOI today with the search and so I just went ahead and started working on this in the iss124-results-limit branch. This should mostly be done (with the default limit of 2000), but I'll switch LOI to the iss124 branch to make sure nothing is broken.

We may very well decide that 2000 is too low for the default; I did just test on MoEML and it rendered 11000 results with absolutely no issue, so maybe the default should be something like 10000?

**Comment by martindholmes** [comment]
@joeytakeda Thanks for working on this. I think MoEML's search is currently very simplistic -- only two desc filters -- but it won't be eventually, so I think 2000 might be a good idea anyway.

**Comment by joeytakeda** [comment]
Testing in LOI and it seems to work perfectly. 

I've put in a PR, but not sure if we should wait to merge until we have the French caption.

**Comment by martindholmes** [comment]
We already have the French caption, so no problem there. I'll merge.

**Comment by martindholmes** [comment]
I've kicked off a few more project builds for some extra testing.

**Comment by martindholmes** [comment]
I believe this is complete and well-tested.
