### ISSUE TITLE
Contexts need to be sanitized to avoid literal XML

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#126]
In the JSON file for each stem, we store the context with the term pre-marked (using the `<mark>` tag) like so:

```
   "context" : "...and is generally not worth reading. It also <mark>elephant<\/mark> has the word elephant three elephant times.",
```

However, if you are indexing escaped XML, then those escaped characters are copied into the context, meaning that if you had something like this:

```
&lt;b&gt;goose&lt;/b&gt;
```

You get, in the goose.json stem file, something like:

```
<b><mark>goose<\/mark><\/b>
```

We should be sanitizing the context strings around the `<mark>`; in part, we need to do this to make sure we're rendering things properly, but also because there is a chance that malicious things could happen--i.e. putting in scripts:

```
&lt;script&gt;alert(` goose `)&lt;/script&gt;
```

As far as I can tell, I think we can get around this by simply double escaping all the preceding and following context strings around the `<mark>` in `json.xsl`. I'm thinking something like:

```
   replace($startSnippet,'&gt;', '&amp;gt;') => replace('&lt;', '&amp;lt;')
```

It's a bit crude, but I believe that should work.

**Comment by martindholmes** [comment]
We may need to consider more possible complicating factors such as the inclusion of `\u1234` JS characters. So the objective has to be that everything that becomes the innerHTML of the kwic output must be fully escaped; in other words, the only actual HTML element in the JSON kwics should be the mark element.

**Comment by martindholmes** [comment]
I've created a branch issue-126-sanitize for this work. I'm going to start by adding some stuff to our tests so that we can see the initial problem.

**Comment by martindholmes** [comment]
Done and merged.
