### ISSUE TITLE
Styling for KWICs with fragment image but not fragment pointer oddly centered

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#127]
When a KWIC with a fragment image has no pointer, the KWIC text centred, which looks a bit odd to me. The elephant example from the test set shows what I mean:

![Screen Shot 2021-02-14 at 12 02 28 PM](https://user-images.githubusercontent.com/17664763/107887665-8a695d00-6ebc-11eb-96d2-08c0ba0dadb9.png)

I would think that we'd want something like a three column grid, where 

```
[FRAGMENTIMG] [CONTEXT]         [FID LINK]

```
Where the context and image are beside each other, the context could stretch to fill the majority of the block if it needs to, and the fidLink is right aligned.

My suggestion is that we:

* Remove `justify-content: space-between`
* Add  `margin-left:auto` to the fidLink to make it right aligned
* Add a right margin of 1rem to the fragment img just to give it a bit of breathing room.

Those changes would yield:

![Screen Shot 2021-02-14 at 11 57 44 AM](https://user-images.githubusercontent.com/17664763/107887645-6148cc80-6ebc-11eb-9d1c-18a42caf79be.png)

**Comment by martindholmes** [comment]
I agree entirely. Go for it, and we can watch what happens in the downstream projects using the dev branch in case of fallout.

**Comment by joeytakeda** [comment]
Done in dev now per 0766f21--works well in the test set, but I think Mariage will be the real test

**Comment by martindholmes** [comment]
Just kicked off a Mariage build -- takes about half an hour.

**Comment by joeytakeda** [comment]
Thanks—just took a look and all seems like it's working to me. I'll keep this ticket open for a bit longer just in case we notice any other oddities in the other projects.

**Comment by martindholmes** [comment]
Looks good. Closing.
