### ISSUE TITLE
Make word-length limit configurable

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#129]
Arising out of the TEI Guidelines test project, it's clear that there are contexts in which searches for two-letter words may be acceptable (element names ab, fw, pc etc.). So I think this option should be configurable, with a warning that if you don't combine it with a good stopword list, it could have consequences for the index size.

**Comment by joeytakeda** [comment]
That sounds good to me. Should there be a separate configurable limit for wildcard length? I.e should you be able to do `a*` ?

**Comment by martindholmes** [comment]
Oh good question. Should we just hard-limit that based on the number of matches in the word list? We've discussed that before.

**Comment by joeytakeda** [comment]
Now that I look at this, we do already have the termLimit thing:

https://github.com/projectEndings/staticSearch/blob/917d7c8f4c707ac57f93dcbf7389b93b381ae1d8/js/ssSearch.js#L328-L331

which is used during the regex expansion:

https://github.com/projectEndings/staticSearch/blob/917d7c8f4c707ac57f93dcbf7389b93b381ae1d8/js/ssSearch.js#L863-L868

But it isn't configurable from the config file, so we should make the termLimit a configurable option as well.

**Comment by martindholmes** [comment]
Actually I don't know if it's worth making that configurable. It's more of a constraint on the network requests you're expecting the JavaScript to do, so I think it would be a bit risky to encourage people to go "what the hell, let's make it a thousand". If you know enough to understand the consequences of this, then I think you know enough to write `Sch.termLimit = 100;` in your search page. I think the things that should be configurable in the config file are things that regular users may need to tweak and play around with for their specific site.

**Comment by martindholmes** [comment]
On the basis of the discussion above, I'm going to leave the issue of wildcard length as a separate one, and implement the configurable term length limit.

**Comment by martindholmes** [comment]
Working on this in branch issue-129-maxWordLength.

**Comment by martindholmes** [comment]
Ready for a PR now.

**Comment by martindholmes** [comment]
I believe this is complete; if we want to address the termLimit configurability question, I think it should be a different ticket.
