### ISSUE TITLE
Only ancestor ids should be used for linkToFragmentId

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#130]
I was under the impression that the preceding fragment id was only used in cases where there was no ancestor fragment id, but that seems not to be the case; testing with the Graves project, it seems that even where there is an ancestor id, if there's a preceding id which is nearer, that one is chosen. That's very problematic because it borks hit-highlighting completely, in a way that can't be mitigated by the project adding ids. So I'm now sure that my original notion that preceding fragments should be used causes more problems than it solves, and I'm going to remove that functionality, working in a branch for testing.

**Comment by joeytakeda** [comment]
I'm a bit perplexed as to why the ancestor id isn't taking precedence over a preceding one, but that's sort of moot since I agree we should get rid of the preceding id behaviour and just stick with ancestor :-)

**Comment by martindholmes** [comment]
I am too. The case in question is in Graves, where there's a footnote which is a div which has an id; inside that div is a footnote number, which also has an id, then the content of the footnote. The indexing of content in the footnote ends up pointing at the id for the preceding footnote number rather than the ancestor which is not what I'd expect, even looking at the code itself. But rather than debug that issue, I think it makes more sense to drop the whole notion of using a preceding id. In my mind at the time I suggested that was the assumption that we would never be able to do hit-highlighting in any reliable way, but that turns out to be completely wrong. I should get out of the habit of assuming that there are things we'll never be able to do. This whole project has undermined that notion completely. :-)

**Comment by martindholmes** [comment]
I'm working in branch issue-130-fragmentid on this, and I'll switch Graves over to use it when I have something to test.

**Comment by martindholmes** [comment]
All working I think.
