### ISSUE TITLE
Not in dictionary check should use same normalization as tokenization

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#133]
Removing the dictionary check from the tokenization stage broke the not in dictionary report, since we're inconsistently normalizing the term. We should use the same function (hcmc:cleanWordForStem) in both the tokenization stage and the not in dictionary reporting so that we get consistent results.

This should happen while addressing #5 as well.

**Comment by joeytakeda** [comment]
Doing this work in the dictionary-fixes branch; it seems to be working locally. Building and testing the TEI set right now to see how it handles it.

**Comment by joeytakeda** [comment]
This and a few other report-related/dictionary-related tickets have all been resolved in the dictionary-fixes branch. Will do a PR now.

**Comment by martindholmes** [comment]
I believe this is now complete, so I'll close it. Thanks!
