### ISSUE TITLE
Question about general index sizes

### ISSUE THREAD

**Issue by wsalesky** [projectEndings/staticSearch#135]
Hi! We are assessing our data storage requirements and trying to gain some idea of how much space Static Search will require. I know there are a few sites running this live, are there any statistics that can help us asses what kind of data storage we should be planning for? Also, I assume at some point the search index stops growing exponentially as there are a finite number of terms we will have. Correct? We are looking at an eventual site with 40-50,000 TEI (small) records in multiple languages. Thanks for the help!

**Comment by joeytakeda** [comment]
Hi @wsalesky ! Great question.

Here's an outline of the various searches for the Landscapes of Injustice project (not yet released); it's technically a multilingual project, but the searches only index the English content (which is the vast majority of it). (Sorry for the big table: it's a bit more detail than what you asked for, but it was a nice way for me to take stock 🙂). 


| Directory                     | Size | Documents | Total Tokens Stemmed | Token Files | Note                                                                                           |
|-------------------------------|------|-----------|----------------------|-------------|------------------------------------------------------------------------------------------------|
| ./TINAsearch/                 | 184M | 10339     | 373174               | 16865       | mostly metadata, some prose                                                                    |
| ./boatLedgerSearch/           | 46M  | 1020      | 104124               | 4016        | mostly metadata, some prose                                                                    |
| ./casefileSearch/             | 187M | 10175     | 358932               | 25884       | has a large paragraph description and a table of metadata.                                     |
| ./fishingVesselRequestSearch/ | 21M  | 94        | 5984                 | 1316        | short documents but with prose (letters)                                                       |
| ./globalSearch/               | 1.3G | 87455     | 3025279              | 87757       | The entire site (so all of the other searches + misc documents); only one desc filter          |
| ./oralHistorySearch/          | 175M | 140       | 579911               | 15458       | Long documents with lots of text                                                               |
| ./personSearch/               | 306M | 50252     | 804935               | 42303       | A document per person, so mostly metadata but with small bits of prose                         |
| ./protestLetterSearch/        | 42M  | 455       | 44284                | 4797        | A document per letter (1 - 2 pages typed)                                                      |
| ./titleSearch/                | 237M | 7398      | 439175               | 41048       | Should be mostly metadata (but I now realize I need to add some words to the stopwords list!)  |

**Comment by wsalesky** [comment]
@joeytakeda Thank you! This is very helpful.

**Comment by joeytakeda** [comment]
One thing I forgot to mention: the directory sizes listed here are all 14M larger than they should be since the dictionary files are being retained (see #119). But by the next release those dictionary files should be removed.

**Comment by martindholmes** [comment]
Closing this since it seems to have been fully answered.
