### ISSUE TITLE
Remove emod and config_moeml

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#151]
We originally had the emod collection and the moeml configuration file in the repo for testing purposes, but we have solid tests in the test folder, and we also have MoEML and many other projects using staticSearch in dev and live, so I don't think these are needed any more. One purpose of emod was to help develop pre-stemmer processing for EME text, but I think we can still do that by pulling files from live or dev projects, which will also give us more flexibility, so I think we should delete these things from the repo. @joeytakeda If you agree, assign this back to me and I'll make the change in dev.

**Comment by joeytakeda** [comment]
Agreed we don’t need the texts in the repo; I’m fine with them being purged. If we end up wanting them again, we can just write a little build process to pull them down a la the TEI set.

**Comment by martindholmes** [comment]
Done in commit # 032cd4c.
