### ISSUE TITLE
Release 1.1 and 1.2 broken and inconsistently versioned

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#152]
Release 1.1 (https://github.com/projectEndings/staticSearch/releases/download/v1.1.0/staticSearch-1.1+2021-01-09.da7331b.zip) is broken due to a missing SVG logo—`buildRelease.xml` doesn't copy over the images directory when building the ZIP, so it doesn't exist:

```
 [java] Error at char 4 in expression in xsl:apply-templates/@select on line 508 column 156 of makeSearchPage.xsl:
     [java]   FODC0002  I/O error reported by XML parser processing
     [java]   file:/Users/takeda/projects/nibs/staticSearch/images/logo_01.svg:
     [java]   /Users/takeda/projects/nibs/staticSearch/images/logo_01.svg (No such file or directory).
     [java]   Caused by java.io.FileNotFoundException:
     [java]   /Users/takeda/projects/nibs/staticSearch/images/logo_01.svg (No such file or directory)
     [java]   In template rule with match="element(Q{http://www.w3.org/1999/xhtml}div)[xs:string(@id) eq "staticSearch"]" on line 254 of makeSearchPage.xsl
     [java] I/O error reported by XML parser processing file:/Users/takeda/projects/nibs/staticSearch/images/logo_01.svg: /Users/takeda/projects/nibs/staticSearch/images/logo_01.svg (No such file or directo
```
Release 1.2 (https://github.com/projectEndings/staticSearch/releases/download/v1.2.0/staticSearch-1.2+2021-03-03.9f0cdfe.zip) contains the same error, but breaks even earlier since `buildRelease.xml` doesn't bundle the CSS directory in the ZIP, so the `copyFiles` task fails:

```
copyFiles:

BUILD FAILED
/Users/takeda/projects/nibs/build.xml:59: The following error occurred while executing this line:
/Users/takeda/projects/nibs/staticSearch/build.xml:316: /Users/takeda/projects/nibs/staticSearch/css does not exist

```

The fix itself in `buildRelease.xml` is fairly simple, but diagnosing this has shored up a number of inconsistencies with naming in releases:

(`tag` being the actual branch tag for the release (which is the release URL `releases/download/TAG/`), generated by us; `name` being the human-readable name for the release that has no real bearing as far as I can tell, generated by us; `ZIP` being the basename for the released ZIP artifact, generated programatically from the `EDITION` file)

* Before 1.0.0, the release ZIP only contains the release number and no date or commit hash
* 1.0.0: 
   * Tag: 1.0.0
   * Name: v1.0.0
   * ZIP:  `staticSearch-1.0.0+2020-10-14.6fb343a.zip`.
* 1.1.0: 
   * Tag: 1.1.0
   * Name: v1.1.0
   * ZIP: `staticSearch-1.1+2021-01-09.da7331b.zip` (Uses *1.1* and not *1.1.0*)
* 1.2.0: 
   * Tag: 1.2.0
   * Name: v1.2 
   * ZIP: `staticSearch-1.2+2021-03-03.9f0cdfe.zip` (Uses *1.2* not *1.2.0*)
* And our current `EDITION` is `1.3alpha`

So we need to fix `buildRelease.xml, re-release those assets, and standardize our EDITION naming practices; we should also add a step to the Jenkins build that checks that our EDITION number conforms to whatever we decide and tests the latest release to make sure it actually works. 

In terms of the EDITION naming, I'd say that our EDITION we should stick to SemVer since our tags already use it consistently. 

In terms of the ZIP asset naming,  I would argue that the release asset should be named `staticSearch-EDITION.zip` without any of the trailing date/commit stamp. That information is already connected to the release via the tag and having it at the end of the URL makes moving from one release to another difficult (unless you have some process that queries the GitHub API and works out the latest name). It'd be much easier to move from release to release if the names just contained the version number, since it would require a very straightforward change to the URL. 

In any case, once we figure out what kind of changes we'll need to make to the `buildRelease` process, then we'll need to figure out how to re-release assets properly, which is the trickier bit. I think—though I need to look into a bit more—that we could make any changes that we need to in `buildRelease.xml` in the `dev` branch, cherrypick that commit into each tag branch (and `main`, I think), and then re-release from each tag.  

Alternatively, we could just re-release the ZIPs by manually fixing them and uploading them thus avoiding any Git acrobatics. The advantage of the cherrypick approach, if it's do-able, is that that anyone ever checking out that tag could build a working release from the source.

**Comment by martindholmes** [comment]
Why don't we simply fix the last release and delete the others? If they're unusable, then nobody is using them. :-)

**Comment by martindholmes** [comment]
Actually, do we need a release package at all? Anybody who can use this certainly knows how to checkout a tag.

**Comment by joeytakeda** [comment]
True, but the release is much nicer to use: you don't need Git to get the stuff and it only contains what someone actually needs and not a bunch of extra stuff (including the history, etc). 

It's only 1.1 and 1.2 that are unusable, so I would say that we should fix 1.1 and 1.2 so that aren't any strange gaps in the process.

**Comment by martindholmes** [comment]
OK, let's do that. Would it be simpler to fix the attached packages, then?

**Comment by martindholmes** [comment]
I just checked the zip for the 1.2 release, and the problem seems to be that two tags were created, and one was made into a release and the other not. I think that's because you started the release and I finished it. So what I think we should do at this point is delete the 1.2.0 tags completely, and start again on that one. For the 1.1.0, we should just add anything that's missing to the zip.

**Comment by martindholmes** [comment]
I've added the images folder to the 1.1.0 zip, so that one should be fine now. That was actually the last one that was release on the main branch, so the 1.2 release was a mess all round. Releases should be done in the main branch. I suggest we delete the 1.2 and replace it with a 1.3 that we craft now. I think we're in a position to do a release right now, aren't we? So:


 - Delete 1.2 tag(s) and release(s).
 - Fix the release build script.
 - Check for anything that would  prevent a release right now.
 - Build and test release.
 - Merge into main.
 - On main, set version to 1.3.0.
 - Build, tag, release.
 - Merge into dev.
 - Set release to 1.4.0alpha.

Sound OK?

**Comment by martindholmes** [comment]
I'm working on getting the release building to a point where we can go for 1.3.0. There are quite a few changes to account for.

**Comment by martindholmes** [comment]
Release 1.3 now replaces 1.2 and no longer includes the distribution package, which is not really useful.
