### ISSUE TITLE
Determine if target: createStemsFile is actually necessary and delete if it isn't

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#159]
I think the createStemsFile target is an artifact of an old approach to wildcards when we were attempting to limit wildcards based off of file size. Needs some investigation, but if we can confirm that the product of that process (`ssStems.json`) isn't used anywhere, then we should just remove it.

**Comment by martindholmes** [comment]
Checking into the JS, the line which retrieved it is commented out and replaced by the one retrieving the ssWordString, confirming what I remember to be the case: we figured that the plain text word list would be faster than the JSON. There's no point at which the file is retrieved either.

I'll remove this in a branch as a final check.

**Comment by martindholmes** [comment]
After a quick look, the changes are trivial so I've just made them in dev. Closing this now.
