### ISSUE TITLE
"Searching" message persists on reset in Safari

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#169]
As noted in #156, the "Searching" message persists in Safari for (to me at least) unknown reason when doing a soft refresh—it doesn't happen every time but happens frequently.

After a bit of investigation, I *think* I've figured out the problem: Safari must have some sort of caching in place such that by the time that the timeout that sets the progress is triggered, the search has already been completed:

```
    setTimeout(function(){
                this.searchingDiv.style.display = 'block';
                document.body.style.cursor = 'progress';
console.log('progress');
}.bind(this), 0);
```

(With added console.log('progress') for me to check when things were being called; the log outputs:

[Log] default (ssSearch-debug.js, line 1950)
[Log] progress (ssSearch-debug.js, line 763)

so it appears that default is being called before progress)

The easiest way to handle this, I think, is to add a  new flag for tracking when a search is happening (i.e. at the start of doSearch()); once that search finishes, we'd set the flag to false. In the timeout, we'd check that flag: `if (!this.searching) return false; this.searchingDiv.style...`

As part of this, we should also duplicate the searchingDiv stuff and shove it into a function; we currently have 9 instances of:

```
this.searchingDiv.style.display = 'none';
document.body.style.cursor = 'default';
```

Which we should probably convert into a function (I'm thinking we may want to shove all of that off into CSS much like the "loading" div, but that would be simple enough once that's a function)

**Comment by martindholmes** [comment]
Agreed on everything. Another thing to consider is whether we should unify the Searching.., and Loading... functionality, since they're really doing the same sort of thing; although that might be tricky because you might end up hiding the Searching... box when your intention was to dismiss the Loading... box. Perhaps all of this belongs in the code_refactoring branch?

**Comment by joeytakeda** [comment]
Good idea re: code_refactoring branch. I'll do that work there, then—I've just updated the branch and am going to tackle this now.

**Comment by joeytakeda** [comment]
I think this should now be handled in the code_refactoring branch—what I ended up doing was:

* Added a new this.isSearching flag in the constructor
* Move all of the searching stuff into the CSS (and made the selector such the searching div only appears if the ssSearching class is set AND ssLoading is not set to avoid the case where they are overlapping) 
* In `doSearch`, set this.isSearching to true
* Then call `setupSearchingDiv()`, which:
    * If the document does not already have an ssSearching class:
        * Add one to the body
        * Then setup a timeout that polls every 100ms to see whether `this.isSearching` is still true; if it isn't, then remove the  `ssSearching` class from the body
        * Then, whenever a search is finished (i.e. in all the places where we had `document.body.cursor...`, we instead simply update the this.isSearching= false, which alerts the timeout that the search has now completed

I've tested on Safari (and the rest of the browsers) and this seems to work perfectly on both test sets. @martindholmes could you please test and see if it's working as expected for you, too?

(I will say, as a sidenote, that I was tempted to rewrite some of this handling to use CustomEvents rather than flags, but that would require some serious thinking, so perhaps something to slate for a future major release if we ever want to perform a more major refactoring.)

**Comment by martindholmes** [comment]
I'll merge the latest dev stuff into this branch and test. I must admit I'm not that keen on the timeout loop. I wonder if we might do this better using MessageEvents? Any thoughts on CustomEvents versus MessageEvents?

**Comment by joeytakeda** [comment]
I was completely unaware of MessageEvents until now, so thanks for that bit of info! From my very brief inspection of the specification, it looks MessageEvents and CustomEvents are both extensions of Event, but MessageEvents are meant more for Server Sent events and message: https://html.spec.whatwg.org/multipage/comms.html#the-messageevent-interface.

I think if we were to move to Events, I think that would be a good candidate for a future release since we may want to do some further refactoring in order to take advantage of the Event interface.

**Comment by joeytakeda** [comment]
Neither of us like the timeout, but per email discussion, I think we decided that we'll leave it in for the time being and think about moving toward a better, event-based system in future. If that's the case, then I think we should close this ticket and I'll open a new one with a summary of thinking about a plan for events.

**Comment by martindholmes** [comment]
Agreed. I've done a bit more reading on the various event models, and I can imagine an approach that would work, but I'm not sure it would gain us much speed or result in less complexity. It needs some thought.
