### ISSUE TITLE
Should we add a noscript element to the search page?

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#177]
I seem to recall a conversation about this, but I can't find any record of it. Since so many of the sites we're building these days start out as pure HTML and have script functionality grafted on at load time, so sites still "work" in the absence of scripting, it might be sensible to provide a noscript element explaining that JS is absolutely required for the search page to work.

**Comment by joeytakeda** [comment]
PR merged and the changes are fairly minor, so I think we're fine to close this and re-open if necessary.
