### ISSUE TITLE
Error in tokenizer on Graves build

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#180]
After many months, I triggered a Jenkins build of the Graves site ahead of some discussions about its future location, and the build failed. The error is:

~~~~~
[xslt] [path-to-file]/graves/svnrepo/staticSearch/xsl/tokenize.xsl:440:13: Fatal Error! Required item type of value of variable $absPath is xs:string; supplied value (fn:resolve-uri(...)) has item type xs:anyURI
~~~~~

I'm also getting lots of warnings about saxon:memo-function not being available in HE:

~~~~~
[xslt] /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/graves/svnrepo/staticSearch/xsl/tokenize.xsl:478:84: Warning! Memo functions are not available in Saxon-HE: saxon:memo-function attribute ignored
~~~~~

which suggests that either an older version of Saxon is being used somehow in place of the one in the staticSearch repo, or there's been a change to Saxon 10 in this respect. I'm currently investigating both issues, but I've raised the ticket in case I don't figure them out in the time available.

**Comment by martindholmes** [comment]
Upgrading the Saxon version in the project's utilities folder seems to have solved the problem, so I have to conclude that the old Saxon 9 that was there was somehow getting invoked during the staticSearch build, rather than the version of Saxon coming along with the staticSearch dev codebase. We should really look into this and figure out how it could be happening.

**Comment by joeytakeda** [comment]
I've checked out the Graves code at  -r 328 (i.e. the commit before you switched Saxon), run the build, and can duplicate the error. Not sure what's happening though, but I'll investigate a bit and see if I can track down the issue.

**Comment by martindholmes** [comment]
I bet you it's this:

`<property name="saxon" value="${lib.dir}/saxon-he-10.jar"/>`

I thought we'd decided to use a custom prefix to avoid this; must have forgotten to implement it.

**Comment by martindholmes** [comment]
It definitely finds its way to the Saxon 9 version in the Graves utilities folder rather than the Saxon 10 in the staticSearch repo. Setting `@inheritall` and `@inheritrefs` to false on the ant call makes no difference.

**Comment by joeytakeda** [comment]
We do use a custom value—`ssSaxon`. I was just typing out that I believe it's due to conflicting -lib and the `<xslt>` task. 

I _think_ what's happening is that the classpath for `<xslt>` task in staticSearch (properly set to `ssSaxon`) is being overridden by the set of jars passed to the Graves build via the `lib` parameter (i.e. `-lib utilities`), which is currently necessary for the schematron task.

Running:

```
 ant -lib utilities buildStaticSearch
```

fails as you mentioned. And `ant buildStaticSearch` fails immediately since the Graves build needs to load the schematron task. But if you comment out all references to the schematron task (and taskdef) in the Graves build and run:

```
ant buildStaticSearch
```

Things work as expected.

**Comment by joeytakeda** [comment]
I'm not sure where to locate responsibility for this, though: is ant's ignoring of the explicit `@classpath` on the `<xslt>` task a bug in ant? Or is this something staticSearch should resolve? Or is this something that should be fixed on the Graves' end?

**Comment by martindholmes** [comment]
Hah! This works:

~~~~~
<exec executable="ant" dir="staticSearch">
      <arg value="-DssConfig=../config_staticSearch.xml"/>
    </exec>
~~~~~

**Comment by martindholmes** [comment]
I've never managed to get a handle on the use of classpaths in ant, especially when one ant task is calling another. This might just be something we want to document for users: either make sure any Saxons likely to be in the classpath are at least as current as the staticSearch one, or call the static search build in a manner which isolates it from the surrounding build process.

**Comment by martindholmes** [comment]
It seems clear that when you call an external ant task from within another one, any parameters passed at the command line to the initial task are inherited by the called task, and there's no way to override this. That means that the -lib directory specified at the command line will be inherited by the staticSearch build.

In one or two projects we've worked around this requirement for -lib; one way is to use @dmj's Schematron implementation instead of the old Schematron task; in other projects we build the Schematron into XSLT when we build the schema, and run/interpret the XSLT ourselves at build time.

**Comment by joeytakeda** [comment]
A third option is to simply run the schematron jar using the Java task—that’s what I tend to do for RelaxNG validation with jing, for instance.

And now that I think of it, we may be able to do something similar instead of using the xslt task (which is where the issue stems, really). We could use an apply and call java/saxon directly (rather than using the Java task), and map the fileset—that avoids the overhead of ant contrib’s loops, and would circumvent the classpath issue.

**Comment by joeytakeda** [comment]
And now that I tested the apply quickly, I realize that of course it won't work—it's doing the same thing (more or less) as the contrib loops, so of course it doesn't go any faster. 

So yes, I think the solution is, for staticSearch, is to simply add documentation about potential gotchas if you're passing a -lib to ant.

**Comment by joeytakeda** [comment]
I've added some docs now to the ODD in the iss180-docs branch. I haven't rebuilt anything since I have a vague recollection that we do not regenerate the HTML output until we build the release, but let me know if I'm misremembering.

**Comment by martindholmes** [comment]
@joeytakeda Thanks for the PR -- made a couple of tiny tweaks and merged, and this can be closed now. I did regenerate the HTML and RNG to test, but didn't commit those changes, just the ODD file tweaks.
