### ISSUE TITLE
Mismatch between implementation and documentation of filter sort keys

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#190]
The documentation currently states that you can use `@data-ssfiltersortkey` to make a sort key for a desc filter, but the XSLT looks for `@data-ssFilterSortKey`:

https://github.com/projectEndings/staticSearch/blob/599d6d6d96051d62294eeafc57d430ade24eafbf/xsl/json.xsl#L858-L860

According to the HTML spec, the documentation is right and our implementation is wrong, since `@data-*` attributes shouldn't contain any [A-Z]:

https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes

So we should insist on `@data-filtersortkey` in the XSLT, but we'll have to be careful so that we don't break any existing projects that had to do the wrong thing in order for filter sorts to work properly. So I think we should:

* In tokenize.xsl, catch any `@data-filterSortKey` and convert it to `@data-filtersortkey`. For now, we should throw a big WARNING that it won't work in the next release 
* Add a rule that disallows `@data-filterSortKey` when implementing #73 (or its superseding ticket). 
* Depending on the results from #73, either we could convert the warning into an error that terminates the build OR we just remove the message completely and let the validator do the work of failing when it catches broken documents

**Comment by martindholmes** [comment]
Wow, I thought we'd dealt with this a while ago. I remember noticing the data-attribute constraint and changing something, but maybe I only changed the documentation and forgot to change the code! We should look at the other data-attributes too.

**Comment by joeytakeda** [comment]
Started working on this in iss190-filterSortKey branch

**Comment by martindholmes** [comment]
This all appears to be working fine so I'll close the ticket.
