### ISSUE TITLE
Need a minor UI tweak for feature filters

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#191]
Right now, when you use a filter feature, the menu of matching options drops down and stays dropped down while you select as many options as you need; then if you click elsewhere in the control or press escape, the menu disappears. However, if you click outside the control, somewhere else on the page, it doesn't disappear, and that's not really intuitive. We need to figure out how to get the menu to disappear when you click away. It could be something as crude as hooking the page's onclick event and sending a message the control can catch.

**Comment by joeytakeda** [comment]
I wonder if the menu hiding could be handled by CSS only? I.e. show the menu only if the fieldset or any of its descendants have focus; something like:

```
.ssFeatFilters > .ssFieldset menu{
 display:none;
}
.ssFeatFilters 
.ssFeatFilters > .ssFieldset:is(:focus-within) menu{
 display:grid;
}
```

Not sure how that might conflict with the javascript blurring, but could be a simple fix?

**Comment by martindholmes** [comment]
I think that's what I started trying to do, but for some reason I couldn't get it working. Probably need to give tabIndex values to things so that focus-within will work...

**Comment by martindholmes** [comment]
Pull request coming on this one from branch issue-191-featmenu.

**Comment by martindholmes** [comment]
I think we're good. Closing! Ready for 1.4 now.
