### ISSUE TITLE
Should we use default values for config items in the schema?

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#194]
Arising out of issue #115: One way to approach the fact that we have de facto defaults for some config items, and don't require that those elements be present in a config file, would be to give those elements default values in the schema. It's not clear to me, though, what the effect of having an optional element with a default value would be. I'm generally suspicious of default values for attributes in schemas, because the actual effect of them is that a user ends up having decisions made for them in their data which are invisible and often unknown to them. However, the case may be slightly different for elements. Looking at the RELAXNG spec, it seems to me that it basically does not even allow for default values for attributes; this is achieved through the using DTD-compatibility annotations. I don't see any way of defining default values for elements. So I don't actually see that we can or should use some schema-based mechanism to specify the default values for configuration element content. @joeytakeda If you agree, we can close this ticket and remove that option from the discussion.

**Comment by joeytakeda** [comment]
You're absolutely right that we can't have any formally defined default values for elements, so we wouldn't be able to do that anyway. I'm going to close this.
