### ISSUE TITLE
Formally deprecated `@data-ssFilterSortKey` for 2.0

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#198]
In #190, we deprecated support for `@data-ssFilterSortKey` by converting it to `@data-ssfiltersortkey` and warning that it will be deprecated in 1.5. This ticket is to remember to do that: all that needs to be done is to remove the template that does the switching in `tokenize.xsl`.

**Comment by martindholmes** [comment]
This was actually deprecated in 1.4.0; for 2.0 we can just change the warning to an error.
