### ISSUE TITLE
When reconstituting a search from URL, we should open any closed details elements

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#199]
It's common to post-process the search page and gather search controls into groups, and I'm increasingly using details elements to organize these and keep the interface a bit cleaner. However, that means that when a search is reconstituted from a bookmarked URL or browser navigation, although controls are correctly configured, they're not necessarily visibly so because they may be inside closed details elements. When reconstituting controls, we should iterate up the tree and open any ancestor details elements. Adding this to 1.4 because I'm going to implement it now.

**Comment by joeytakeda** [comment]
That sounds good to me—though, if possible, we'll want to structure the function carefully so that it can be removed (I'm just thinking about my own projects that I have a similar set up already that may break due to the new function, but c'est la vie)

**Comment by martindholmes** [comment]
Yes, I'm preparing to go back and fix a couple of existing projects myself. But I don't think anything will necessarily break; it'll just try to do the same thing over again, presumably, and find that it has nothing to do. I'm testing my initial implementation now.

**Comment by martindholmes** [comment]
Pull request is ready.

**Comment by joeytakeda** [comment]
@martindholmes : any reason not to close this now? (I don't have any details in my projects, so can't confirm if it's working or not)

**Comment by martindholmes** [comment]
It's working nicely in DVPP. I'll close it.
