### ISSUE TITLE
Number filters may not be restored onpopstate

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#203]
For once I have a project that is using number filters, and I noticed that the filter values are not restored from the url query string when navigating back to a search, nor is a search triggered. I need to look into this carefully because the search page on that site is being heavily post-processed to rearrange the controls, so there could be something anomalous about the page which is causing this, but the number filters themselves are working for searches, and other controls are being successfully restored as normal, so it's possible this is a bug we haven't noticed because number filters are used so infrequently in our projects.

**Comment by joeytakeda** [comment]
I can duplicate the bug on the live LOI site, so it has been lingering for quite a while now—thanks for catching this!

**Comment by martindholmes** [comment]
I wonder if we could add this into our testing somehow. The popstate stuff seems fairly crucial to me.

**Comment by martindholmes** [comment]
Working on this in branch issue-203-popstate.

**Comment by martindholmes** [comment]
I have one fix in place: we were erroneously testing the length of the numeric value against 3, and ignoring if it was less. Having fixed that (in the branch), the correct values are now being restored, and the search is triggered, but now it mysteriously fails to find any documents.

**Comment by martindholmes** [comment]
It appears that when the getDocIdsForFilters method runs on a page reload, all the required JSON may not yet be loaded; StaticSearch.allJsonRetrieved reads as false at the point where that method is looking for the filter's entry in the mapFilterData map, and therefore the filters are not used. I need to find the checks which run before the search is triggered, which are supposed to queue up the JSON for any filters required to do the search, and refrain from triggering it until they're all retrieved, but that seems to be failing for number filters.

**Comment by martindholmes** [comment]
Found it: another instance of checking the length of a number is at least three. Pull request coming.

**Comment by martindholmes** [comment]
I'll wait for DVPP to build to test this in a real proj, then close if all is good.

**Comment by martindholmes** [comment]
Confirmed fixed on DVPP too, so I'll close this.
