### ISSUE TITLE
Consider adding headless browser testing

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#204]
I’ve been chewing on this for a bit and with #203 I think we have another good reason to create some real browser integration tests to staticSearch. It’s not a trivial thing to do, of course, but probably worth doing to make sure we have good coverage of the code. 

The main issue is that, other than Selenium, the only good way to do these tests is through node packages (like Puppetteer or Playwright), which I know we don’t want to support in our Jenkins build. However, I think we could do this all with GitHub actions — I’ve been experimenting with something similar in the WEA and it works really well with the added advantage of not having to support node packages on a server we maintain.

In addition to the Jenkins build, we could run the full build in GitHub actions, spin up a server, and then test that the regular test suite works properly (ie open the page and wait until all of the tests successfully complete), and then hit it with a number of other tests for things like popstate checking. The only modification is that we’d have to have some way for the test page to know not to run the tests and to store its results in the browser history (either we simply copy the page and remove the call to the testing script or we send a flag or something). 

As much as I’m wary of ever relying on node packages, I think this is still within Endings acceptability: the code itself isn’t necessarily meant to be preserved and these tests would be run on in GitHub and outside of the regular build.

**Comment by martindholmes** [comment]
Agreed. I think the thing to do would be to add a final transform which copies the test search page but removes the test call, then have puppeteer or playwright load the page, configure all the controls, do a search, do another one, then press the back button. Then we check the current values of the controls and the search results to ensure they're as expected.

**Comment by martindholmes** [comment]
Setting to 1.5 because I would like to get 1.4 out this month.

**Comment by joeytakeda** [comment]
Have started work on this in a branch `headless_test` (which is badly named as I had forgot that I had raised this ticket before 🙃) 

At the moment, the branch just checks for the existence of the search pages as well as confirms that all (in page, built-in) tests work.
