### ISSUE TITLE
FR: new ideas for the config file

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#21]
I'm realizing that for varied document collections it's going to be a good idea to present completely separate search pages for different document types, while also allowing people to search the entirety of the collection. That will require multiple indexing operations over the collection, and needs some enhancements:

1. XPath that selects only a subset of the entirety of the documents for indexing.

2. The option to provide a specific folder for storing the JSON on the search site and accessing it from a search page, so that multiple index collections can exist side by side.

3. The option to specify HTML meta tags which should be ignored during a specific indexing option. For example, if I have a bunch of people pages, then I want the search engine that's targetting only people to pay attention to metatags with birth and death dates, and create controls on the search page for that; but if those documents are being included in a bigger search-everything operation, I need to suppress processing of those tags, because birth and death dates are not relevant to the majority of documents on the site, and such a control would be confusing in the context of a bigger search engine.

This isn't too complex a change, but it enables a whole range of functionality for larger sites which will be really powerful. It's going to be essential for (for example) the Despatches, DVPP and MoEML sites.

**Comment by joeytakeda** [comment]
This sounds like a good idea to me. I will be interested to see how large the JSON collections get, since we're going to end up with many near duplicate files. 

How might this interact with #20 ?

**Comment by martindholmes** [comment]
I think it would make #20 obsolete, or at least make it a lot less of a priority; I think for our own projects, this approach solves more problems and allows more flexibility than #20 would.

**Comment by martindholmes** [comment]
I see no reason not to leave #20 as a possibility, though; it will be much simpler for most users to configure and may be sufficient for lots of smaller sites.

**Comment by martindholmes** [comment]
Implemented item 2 in commit 890f6a2. Next is item 3 (not too hard), followed by item 1 (probably the trickiest).

**Comment by martindholmes** [comment]
For item #3 (XPaths for inclusion and exclusion), I propose the following:

 - A new `<selections>` element which is a sibling of `<params>`.
 - Child `<include>` and `<exclude>` elements with two attributes:
 -- `@type="documents | filters"` (meaning used to include or exclude documents from indexing, or filters from being used in the search page).
-- `@xpath="XPath"` (specifying XPath to select such documents or meta tags).

These values would be written to the config file in the form of variables selecting those documents and filters. Before any document is processed, it would be checked to make sure it qualifies to be included (meaning it's in the include list, or there isn't one; and it's not in the exclude list, if there is one). Each filter would be processed in a similar way. Allowing both includes and excludes will make the process a little harder for us to code, but way simpler for the user to configure. Excludes always trump includes, so if your include XPath and your exclude XPath both match the same document, the latter wins and it's excluded. Ditto for filters. One obvious example usage would be excluding the search page itself from the indexing. The default namespace is of course the XHTML namespace.

Thinking of some examples:

 - In a nested-folder site scenario, you might exclude `//html[contains(document-uri(.), '/obsolete/')]`.
 - In a site like DVPP, where person pages have ids beginning with "prs_", you could include `//html[starts-with(@id, 'prs_')]` to create a search only for people.
 - In a document search which is intended to exclude people, you might exclude filters like `//meta[@name=("Date of birth", "Date of death")]`.

One wrinkle we'll need to consider: if you put in an XPath which selects only part of a document, such as `//p[@class='noIndex']`, do we either: ignore it, because we expect documents to be selected; assume it means the containing document, and should have been framed as `//html[descendant::p[@class='noIndex']]`; or actually honour it, by indexing the document but not the part that's specified? The first option is tempting, but the last would be very cool indeed, although perhaps a lot more work.

**Comment by joeytakeda** [comment]
I'm a bit confused by the relation between `@type` and `@xpath`...does it ever make sense to have an `@type='filter'` and an xpath that is not a `<meta>`?

That is, is this legal:

```
<exclude type="filter" xpath="p[@class='noIndex']"/>
```
or should this be a static error?

> One wrinkle we'll need to consider: if you put in an XPath which selects only part of a document, such as //p[@class='noIndex'], do we either: ignore it, because we expect documents to be selected; assume it means the containing document, and should have been framed as //html[descendant::p[@class='noIndex']]; or actually honour it, by indexing the document but not the part that's specified? The first option is tempting, but the last would be very cool indeed, although perhaps a lot more work.

I like the third option, which I think we could do by performing a similar operation as we do for weighting: we add a data attribute like `data-staticSearch-ignore="true"`. This would tell the tokenizing templates to NOT tokenize that bit of the document; however, it would NOT exclude it from the KWICs. So, for instance, let's say we've tagged all instances of "thou art" in a sentence:

```
<div data-el="l"><span class="thouart">Thou art</span> more lovely and more temperate</div>
```

If we do something like:

```
<exclude type="document" xpath="span[contains-token(@class,'thouart')]"/>
```

The end result could look something like:

```
<div data-el="l" data-staticSearch-context="true"><span class="thouart" data-staticSearch-ignore="true">Thou art</span> <span data-staticSearch-stem="more">more</span> [...]</div>
```

This is different from setting a weight of 0, of course: the weight of 0 _deletes_ the element from the flow, effictively removing it from KWIC harvesting etc. Setting an exclude would allow Thou art to be included in the KWIC for "love", but that instance of "art" would not be included in art.json. In other words, the tokenizing template would need to change to something like:

```
<xsl:template match="text()[not(ancestor::*[data-staticSearch-ignore])]">
```


That we, if we want to specify that the whole document be ignored, we'd do precisely as you state above:

```
<exclude type="document" xpath="html[matches(@id,'sonnet_\d+')]"/>
```

**Comment by martindholmes** [comment]
You're right, I wasn't thinking clearly about the `@type` attribute. I was assuming that it would be way easier to process these things if they're pre-configured as one type or the other, rather than having to follow the XPath to determine whether they're referencing filters, documents or (now) parts of documents. I guess we really want `@type="index|filter", and if a filter XPath doesn't match a filter, then it doesn't do anything.

But although being able to specify any old element for exclusion is nice, how is it going to interact with inclusion? If a parent is excluded and a child included, what happens? Having thought about this for a while, I think a better approach might be to dispense with includes altogether so we can avoid this complication. 

I do like the idea of sophisticated exclusions like "thou art". Turning it around, you could have this:

`<exclude type="document" xpath="*not(ancestor-or-self::span[@class='name'])"/>`

and get an index only of the names in the documents. Useful? Not sure. Not easy to code for correctly, though.

**Comment by martindholmes** [comment]
Should this be closer to the `@match` attribute rather than allowing any-old-xpath?

**Comment by joeytakeda** [comment]
> Having thought about this for a while, I think a better approach might be to dispense with includes altogether so we can avoid this complication.

Yes, I think we should only handle exclusion or we only handle inclusion, and I think exclusions make most sense—the default assumption, I think, is that you want to stem everything EXCEPT some things, rather than stem nothing and then select the particular things you want. 

> Should this be closer to the `@match` attribute rather than allowing any-old-xpath?

Right now, the `@xpath` element in the specification outlines that it's meant to follow the XPath rules of a `@match`. Perhaps we ought to change it to `@match`?

**Comment by martindholmes** [comment]
I think I agree; `@match` makes more sense. That's a backward-compatibility-breaking change, but we're only at 0.7, so no big deal. :-)

So should the section be called `<excludes>` instead of `<selection>`?

**Comment by joeytakeda** [comment]
@martindholmes I think I have an initial approach for this now working in the XSLT. Here's a summary of what I've done:

1. Added `<excludes>` and `<exclude>` to the ODD (note that it still uses `@xpath` and not match)
1. Added handling for `<exclude>` in the tokenizing step by adding another template pass where the documents (or fragments) are given an `@data-staticSearch-exclude` attribute if they are meant to be excluded
1. Modified `json.xsl` to only produce filter files from metas without `@data-staticSearch-exclude`, which has the knockoff effect of being excluded from the search page creation process entirely
1. Added a few extra reports to the report page to show which documents have been excluded and which filters are to be excluded. 

How does this look to you?

**Comment by joeytakeda** [comment]
Missed a spot, which I've now addressed in https://github.com/projectEndings/staticSearch/commit/941957f9837ac0ff9a5c275c24e15d24f14e5b54. Documents that are being excluded from the search should not show up the filter docs list at all.

**Comment by martindholmes** [comment]
Not sure if I'm running this properly, but when I use configTestWorthReading.xml, it seems to list four excluded files twice over in the report:

badthings
poems_ditty
search
poems_per_decade_year
badthings
poems_ditty
search
poems_per_decade_year

Running a search also returns two sets of results. So I'm not quite sure what's happening here...

**Comment by joeytakeda** [comment]
That's odd indeed. 

Cloned a fresh copy of the /dev/ branch and stashed it in another folder to test and I get the expected results.

Running

```
ant -Dconfig=testConfigWorthReading.xml
```

gives me this as a report:

![_Users_joeytakeda_work_ssTestNew_staticSearch_test_ssWorthReading_staticSearch_report html](https://user-images.githubusercontent.com/17664763/74626523-c41a5300-5104-11ea-8f57-58074ea444dc.png)


And with the proper search results.

Running both searches sequentially:

```
ant; ant -Dconfig=testConfigWorthReading.xml
```

also gives me the right results for both search pages; all of the automated tests in search.html pass. So I'm not sure what's happening here...

**Comment by martindholmes** [comment]
When I run exactly what you ran, the first build succeeds but the second fails:

~~~~~
BUILD SUCCESSFUL
Total time: 13 seconds
Opening in existing browser session.
Buildfile: /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/build.xml

init:
   [delete] Deleting: /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/xsl/config.xsl
    [mkdir] Created dir: /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/staticSearch

validate:
     [echo] Validating /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch for well-formedness
[xmlvalidate] /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/lib/saxon_docs/index.html:26:32: The entity "nbsp" was referenced, but not declared.

BUILD FAILED
/media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/build.xml:78: Could not validate document /media/mholmes/06eac294-b7ff-42b8-b3cc-ab40279fa597/mholmes/DiskStation/mholmes/WorkData/endings/staticSearch/lib/saxon_docs/index.html
~~~~~

**Comment by joeytakeda** [comment]
That's very strange--to me, it looks like Ant isn't able to find the directory specified in the configTestWorthReading.xml. The config file specifies it properly--test/searchWorthReading.html--but that search page doesn't actually exist yet; it should be created by the search process (per #39). 

A wild guess: maybe the issue is this line in the Ant file:

```
<property name="searchFilePath" location="${configDir}/${config.params.searchFile}"/>
```

Maybe Ant doesn't resolve a `@location`, in some version of Ant, if the file doesn't exist. What version of Ant are you running? I'm running Apache Ant(TM) version 1.10.6 compiled on May 2 2019.

**Comment by martindholmes** [comment]
Ant 1.10.5 (default repo version on Ubuntu 18.04). I think this is the first case in which I've run a build process for which the search page doesn't yet exist. When I have a chance I'll try to nail this down. 

Doesn't configDir get constructed based on the location of the search file? If so, we have a circular definition going on.

**Comment by martindholmes** [comment]
OK, I can now run the process; not sure what was failing yesterday. The first time I run it, I get four excluded documents; the second time I get five, because now the search page exists.

One run of the process caused the existing tests to fail for some reason, but subsequent runs seem to be OK. So I think there is something odd going on, but I'm not sure what. We should implement some automated tests in the searchWorthReading page too, to make sure that what we believe is being excluded from those indexes is in fact being excluded. 

I think it might be prudent to keep the early modern stuff in a separate test folder, since what we want to test there is a rather different sort of thing. In fact, the only thing (I presume) we need to test there is the behaviour of the two stemmers (or, more likely, pre-processors for the regular stemmers).

**Comment by joeytakeda** [comment]
I've now added tests in searchWorthReading.html (which now has to be stashed in the repo in order to have the set of tests). I've updated all the values from search.html and added a new test for a specific word ("ignominious"), which should only exist in badthings.html (and thus isn't worth reading).

**Comment by martindholmes** [comment]
That's excellent! I should be able to test this out for real in DVPP this coming week.

**Comment by joeytakeda** [comment]
Now that I start playing with this a bit, I think we can make a few improvements that will help with efficiency and memory consumption:

1. Exclusion should be the very first template that runs in the XSLT
1. If there are no exclusions declared in the config, then don't even use the variable: i.e. something like:  `if ($excludesDeclared) then $excluded else .` in the next template
1. If exclusions are declared and, after the document is passed through the exclusion template, the root `html` has a `data-staticSearch-exclude='true'`, then don't bother passing it through any of the other templates. Just move on to the next file and don't  create a `_tokenized.html` file from it.

**Comment by martindholmes** [comment]
I've now tested this in DVPP and it's working well, so I'm going to close this ticket; the optimization stuff could be moved to a ticket which is more specific.
