### ISSUE TITLE
Add `@version` attribute to config file 

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#215]
As per email discussion, the root `<config>` element should contain an `@version` attribute that specifies the major staticSearch version to which the config corresponds; this will make transforming older versions of the config file simpler if we change the configuration structure (as discussed in #195)

**Comment by martindholmes** [comment]
Let's make this a single integer value, forcing us to stick to our decision that compatibility-breaking changes only happen in major version changes.

**Comment by joeytakeda** [comment]
Just added `@version` as a recommended attribute on the config element in  branch iss215-version. Added some documentation about it as well as some more documentation about the root config element as well as a paragraph with some pointers to examples of full config files. (As we discussed before, we  should probably give more and better examples directly in the prose, but that's another ticket for another day and another release, I think).

Will do a PR now—please feel free to dip into the branch and correct / finesse things as you see fit :-)

**Comment by joeytakeda** [comment]
Added, but forgot to close before the release! Closing now.
