### ISSUE TITLE
Results in chronological order rather than sorted by score

### ISSUE THREAD

**Issue by martinantonmueller** [projectEndings/staticSearch#217]
We edit a diary/journal. So an often used search is to look for the first appearance of a term. Is there a possibility for the output of the search results to be in chronological order rather than based on score?

**Comment by martindholmes** [comment]
We do have the document sort key feature:

https://endings.uvic.ca/staticSearch/docs/howDoIUseIt.html#configuringDocSortKey

If you create your sort keys as ISO dates, then they will naturally sort in order. However, this is normally overridden by the hit score, so to get a true date-based sort, you may have to override the method SSResultSet~sortByScoreDesc:

https://github.com/projectEndings/staticSearch/blob/v1.4.0/js/SSResultSet.js#L315

to make it disregard the score and use the sort key instead. @joeytakeda, do you think we should make this configurable?

**Comment by martinantonmueller** [comment]
Perfect! Thank you!

**Comment by joeytakeda** [comment]
We have a similar ticket for this already: #86 and I think it is certainly something worth revisiting
