### ISSUE TITLE
Delete unnecessary config items

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#218]
Per #195: We are no longer going to support the config items:

* `<verbose>`: should be replaced with a single command line option passed to ant
* `<indentJSON>`: should just be removed (I don't think it's necessary at all, really, since it's easy enough to format JSON in firefox or using `jq` etc)
* `<scrollToTextFragment>`: scrollToTextFragment since it will probably never be supported anyway
* `<linkToFragmentId>`: should just be the default behaviour (one can always hide the `.fidLink` if they don't want the behaviour)

For each, we need to check for handling in the XSLT modules and the JavaScript (I think only scrolltoTextFragment will be mentioned there) and note this in the documentation.

We should also start adding these things incrementally to the 1.0 -> 2.0 transformation; I'll start that file now even though we won't have full handling for it yet.

**Comment by joeytakeda** [comment]
Starting work on this in branch iss218-deletions

**Comment by joeytakeda** [comment]
In branch iss218-deletions, I have now deleted scrollToTextFragment, linkToFragmentId, verbose, and indentJSON from the schema, updated all of the documentation, and removed (or, in the case of verbose, modified) handling across the XSLT and Javascript.

In the process, I've added a new transform in `xsl/`: `xsl/convert_v1_to_v2.xsl` . That transformation is still a draft: it isn't called by anything, but I thought it worthwhile to add the migration handling in step with the rest of the deletions for configuration options.

**Comment by joeytakeda** [comment]
Here is the change set for the branch:

https://github.com/projectEndings/staticSearch/compare/iss218-deletions

I've tested with the test set and all seems to work well, but it would be best to test with some real projects before I do a PR. For my own projects, I'm thinking that I might add a switch such that I can switch them from `/main/` to `/dev/` and use a corresponding config file (i.e. v1 for main, v2 for dev).

**Comment by martindholmes** [comment]
Lots of lovely cleanup there! Thanks indeed. I've looked at everything and made a couple of additional cleanup changes. Everything works for me in the test. I would like to identify a larger project I could use for testing, and actually Graves might be it, since it's been staticized and archived with the Library, so in theory there should be no further need for me to change it, meaning it can be a sacrificial testbed.

**Comment by martindholmes** [comment]
Already merged. Closing.
