### ISSUE TITLE
Feature filter values should sort alphabetically

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#227]
I have one very large (13,000+) feature filter for poem titles in DVPP, and I'm noticing that one of the most valuable things you can do with it is to type (e.g.) "Sonnet" and see all the titles that contain the word "Sonnet". However, if you want to find the exact title "Sonnet", you have to scroll through a lot of unsorted options. So I think feature filters should be sorted alphabetically by default in the JSON, which I think would carry through into the drop-down menu in the filter control.

**Comment by martindholmes** [comment]
I wonder if I should have lower-cased the grouping key first... I can't think of a reason not to do that, can you @joeytakeda?

**Comment by martindholmes** [comment]
In other words, `<xsl:sort select="lower-case(current-grouping-key())"/>`.

**Comment by joeytakeda** [comment]
I can’t see any reason not to—seems like the right thing to do to me

**Comment by martindholmes** [comment]
Done in dev. I'll close the ticket and delete the branch.
