### ISSUE TITLE
A new error for me

### ISSUE THREAD

**Issue by lyallg** [projectEndings/staticSearch#229]
Hi guys. I seem to recall you want issues/questions submitted here instead of email? If this isn't the right spot for this let me know. 
I am not sure if this is a source data issue I haven't done anything (I believe) that would cause a break in SS build, I can build XML to HTML ok. Here is error:

`tokenize:
     [echo] Creating tokenized XHTML files...
     [xslt] Processing /mnt/d/Stuff/Bizness/GLRD/site/Archive_Alden-SeabirdBar.html to /mnt/d/Stuff/Bizness/GLRD/site/search/ssTemp/Archive_Alden-SeabirdBar_tokenized.html
     [xslt] Loading stylesheet /mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/tokenize.xsl
     [xslt] /mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/config.xsl:27:80: Fatal Error! Duplicate global variable/parameter declaration (see line 36 of file:/mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/config.xsl)
     [xslt] Failed to process null

BUILD FAILED
/mnt/d/Stuff/Bizness/GLRD/build.xml:459: The following error occurred while executing this line:
/mnt/d/Stuff/Bizness/GLRD/staticSearch/build.xml:236: Fatal error during transformation using /mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/tokenize.xsl: Duplicate global variable/parameter declaration (see line 36 of file:/mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/config.xsl); SystemID: file:/mnt/d/Stuff/Bizness/GLRD/staticSearch/xsl/config.xsl; Line#: 27; Column#: 80`

It's failing on very first document. Thanks.
- Gord

**Comment by martindholmes** [comment]
Hi @lyallg. If your project is configured to use the dev branch, switch it to the main branch; we have backwards-incompatible changes landing in dev now. Release 1.4.1 is on the main branch and it should work for you.

**Comment by lyallg** [comment]
@martindholmes Ok. That did it. Thanks for the lightning quick reply. You can close the ticket.
