### ISSUE TITLE
The child of contexts should be context

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#23]
Right now, the config file containers `<rules>` and `<contexts>` both have `<rule>` children. In fact, the children of `<contexts>` should be `<context>` elements, as the documentation shows. This change would also enable us to add an `@name` attribute to a context, allowing (possibly, in the future) a "Search only in" sort of function -- "Search only in editorial notes", for example. I suggest adding the `@name` as an optional attribute anyway, so that people can use it to document what their contexts are; if we later decide to use it, we can do that.

**Comment by joeytakeda** [comment]
Agreed; this will also mean fleshing out the documentation slightly to include what the name attribute means in this context. On the docket for beginning of January.

**Comment by martindholmes** [comment]
Fixed this in commit https://github.com/projectEndings/staticSearch/commit/e6800ad6aa9a782359aa55519f8eb3dabef64287. Closing, although WEA config file will have to be updated.
