### ISSUE TITLE
Cleaning up old cruft, and doing a release

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#24]
I'd like to think ahead to doing an actual release (maybe 0.7?) with the current state of the dev repo. This will mean cleaning up a lot of the cruft that's gathered, something I've already started on. This is what I'd like to do:

1. Delete everything related to "test" (the original test data), including all the Travis stuff. It isn't documented anywhere, and as far as I can tell it doesn't actually work. That would mean getting rid of the site folder and its contents, the config.xml file, the test folder and its contents, and the buildTest2.xml ant file. 
2. Rename test2 to test.
3. Rename config_2.xml to configTest.xml.
4. Rewrite the build.xml file so that it assumes by default that it's building the test materials, but if you supply a different config file it builds based on that file.
5. Delete buildTest2.xml.

That would clear out all the old test stuff and the Travis stuff (although you could add it back if you want to in its own folder, like the jenkins integration has its own folder). 

Finally, I'd like to then merge dev into master (a bit tricky -- there are three commits to master that probably shouldn't have been there), and then do a tag as a release. That would mean that we could tie svn projects to that specific tag, rather than choosing between the master or dev branches, and whenever a new tag/release is done, we can take as long as we like to update projects.

@joeytakeda is this OK with you?

**Comment by martindholmes** [comment]
I'd also like to remove staticSearch-lite.odd from the repo as it's a generated file from the schema build process. Any reason not to do that?

**Comment by joeytakeda** [comment]
This all sounds good to me, though I wonder if we should just call this release 1 or 1a or 0.1 or something like that? I’m not a huge fan of starting with 0.7 as a release, since, at least in my mind, it implies prior releases; alternatively, I think we could retroactively tag particular commits as release 0.1-0.6, just so that it’s clear in the release history what we’ve done for historical purposes.

**Comment by martindholmes** [comment]
I picked 0.7 because I'm thinking that there are about two more major features we'll want to add before we're happy with the feature set, one being the support for multiple search pages across the same dataset, and the other being glob support. One would get us to 0.8, then next to 0.9, and then 1.0 would be a fully cleaned-up, optimized and bug-fixed version. Make sense?

**Comment by martindholmes** [comment]
Done and dusted; repo is leaner and meaner.
