### ISSUE TITLE
Rename attribute for a fractional speed increase

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#241]
The attribute `data-staticSearch-relativeUri` is created and used only during the tokenizing and JSON steps, so it doesn't need to be a valid HTML attribute value, and could be renamed to `ss-uri` to reduce the size of tokenized files and optimize i/o and parsing a bit.

**Comment by joeytakeda** [comment]
Will do this now -- branch issue-241-ss-uri

**Comment by joeytakeda** [comment]
PR ready now

**Comment by martindholmes** [comment]
Thanks @joeytakeda. Merged, closing now.
