### ISSUE TITLE
Tokenizer bug: fails to tokenize on linebreaks

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#25]
An HTML structure like this:

~~~~~
<h3><span class="a">The Story of Sir Arnulph</span><br/>Metadata</h3>
~~~~~

results in a token "ArnulphMetadata". I think the tokenizer should treat a `<br/>` tag as whitespace.

**Comment by joeytakeda** [comment]
Seems reasonable. Are there any other elements that ought to be considered word separating?  <hr/>?

**Comment by martindholmes** [comment]
I think the list on this page:

https://developer.mozilla.org/en-US/docs/Glossary/Empty_element

Cheers,
Martin

**Comment by joeytakeda** [comment]
Those all look good except <wbr/>, which by definition is in the middle of a word, so that should be simply removed.

**Comment by martindholmes** [comment]
@joeytakeda Is this complete?

**Comment by joeytakeda** [comment]
Yes, I believe so, but I was only able to test via Jenkins and not on the project that shored the error up (DVPP?) But as far as I can tell it’s working properly.

**Comment by martindholmes** [comment]
What I'll do is build this into the tests, so we can check for sure. I tweaked DVPP to avoid the problem by adding spaces.

**Comment by martindholmes** [comment]
Test added; works fine. Closing.
