### ISSUE TITLE
<linkToFragmentId> not in RNG schema

### ISSUE THREAD

**Issue by tgraham-antenna** [projectEndings/staticSearch#253]
`<linkToFragmentId>` is not present in https://github.com/projectEndings/staticSearch/blob/d98f80599dbe28582758424d0097e964e95dc1db/schema/staticSearch.rng

**Comment by tgraham-antenna** [comment]
I see now that `linkToFragmentId` was/is removed by #218, but it's still documented at https://endings.uvic.ca/staticSearch/docs/schemaSpec.html#TEI.linkToFragmentId

**Comment by martindholmes** [comment]
@tgraham-antenna The documentation on the Endings site is for the current stable release (1.4.2), so it won't match what's in the dev branch. The current dev documentation explains that it has been removed from the schema because it's going to be the default behaviour from 2.0 on.
