### ISSUE TITLE
ant-contrib should be included in the repo

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#260]
Since `ant-contrib` is a simple JAR, we should include it in the repository rather than force end-users to install it separately.

**Comment by peterrobinson** [comment]
Cool idea. If you can. Check out what I had to do at [https://scholarlydigitaleditions.blogspot.com/2023/07/staticsearch-and-me.html](https://scholarlydigitaleditions.blogspot.com/2023/07/staticsearch-and-me.html) to get the right jars.

**Comment by sydb** [comment]
I am in favor of at least including ant-contrib in the repo, if not actually removing reliance on it. (Personally I really like ant-contrib, but I recognize that I like it out of laziness.)

A quick search says that ant-contrib is only used 5 times in the build files within the 1.4.5 release, all in the main build.xml file:

- `<if>` is used 4 times (on lines 155,177, 194, and 307)
- `<propertyregex>` is used once (on line 345)

**Comment by joeytakeda** [comment]
This should now be handled by PR #291 — adding ant-contrib to the staticSearch repo works and doesn't seem to conflict with having a local ant-contrib, so closing this.
