### ISSUE TITLE
Add emacs snippet to documentation

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#266]
Thanks to @tgraham-antenna in #254 , we have some instructions for Emacs use with RNC—this should be added to the documentation:

```
<?xml version="1.0"?>
<!-- Schema locating rules for use with Emacs' 'nXML' mode. -->
<locatingRules xmlns="http://thaiopensource.com/ns/locating-rules/1.0">
  <namespace ns="http://hcmc.uvic.ca/ns/staticSearch" uri="staticSearch.rnc"/>
</locatingRules>
```

**Comment by martindholmes** [comment]
On balance, we think Emacs users will already know how to do this, and we don't think it's worth adding Trang to the repo just to generate an .rnc file which will only be used by a small number of people who know how to generate it anyway. This ticket will be findable for anyone who is interested.
