### ISSUE TITLE
FR: Split diagnostics report into multiple files

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#27]
For large projects, the diagnostic report can become enormous—MH reports that DVPP is at about 30MB. We want people to be able to open these files quickly, so I suggest we split the diagnostics report into multiple small files, linked by an index file and TOC, akin to the XSLT documentation produced by oXygen.

**Comment by martindholmes** [comment]
Probably not happening before the 1.0 release, so pushing it to 1.1.

**Comment by martindholmes** [comment]
This is another nice-to-have, but not urgent. @joeytakeda Shall we push it to 1.2?

**Comment by joeytakeda** [comment]
Yes, let's push this to 1.2.

**Comment by martindholmes** [comment]
@joeytakeda I think this is a nice-to-have, but nobody's clamouring for it, so I'd suggest we kick it to 1.3 for now. What do you think?

**Comment by joeytakeda** [comment]
Yes, agreed—I’d like to spruce up the display a bit, too, so might as well do it all properly.

**Comment by martindholmes** [comment]
We can close this ticket because the changes resulting from OOM errors mean that the report itself is smaller and the concordance and similar content will probably end up being spun out into a separate process and output.
