### ISSUE TITLE
xmlvalidate task looks at files that it shouldn't

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#274]
On line 217 of build.xml, the include for files to check for well-formedness is:

`<include name="**/**.*htm*"/>`

However, the documents we actually want to process, as defined in tokenize.xsl, are:

`<xsl:variable name="docRegex">(.+)(\..?htm.?$)</xsl:variable>`

This means that documents we will not process may be checked for validity. @sydb found this when renaming files to ".nothtml".

**Comment by martindholmes** [comment]
The immediately obvious solution is:

`<filename regex="(.+)(\..?htm.?$)"/>`

and I assume we also don't need the capturing groups just for a match. I'll test this.

**Comment by sydb** [comment]
Though wouldn’t it be nice to let the user pass in a regex to match from the commandline?

**Comment by martindholmes** [comment]
@sydb It might be nice indeed. But that's not the bug. :-) We'll fix the bug first, then wait for a user to raise a feature request.

**Comment by martindholmes** [comment]
@joeytakeda I've just fixed this in the 1.4 release branch, and I'll do a release when a couple more things are fixed. Meanwhile there's a PR for it on the dev branch, assigned to you.

**Comment by martindholmes** [comment]
PR was merged. Closing.
