### ISSUE TITLE
FR: Make `<form>` display:flex for ease of re-ordering objects

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#29]
By default, objects in the form are ordered:

* Query Box and Button
* Desc Filters
* Date Filters
* Boolean Filters

If we make the `<form>` item display:flex, then users can take advantage of the `order` property to shift the position of the objects simply.

I think adding:

```
form{
display:flex;
flex-direction:column;
}
```

and 

```
span.ssQueryAndButton {
    display: flex;
    flex-direction: row;
    margin: 0.25em auto;
  +  width: 100%;
}
```

Would do the trick.

**Comment by martindholmes** [comment]
Agreed! Go for it.

**Comment by martindholmes** [comment]
Done in commit c8b6291.
