### ISSUE TITLE
citations are indexed invisibly — `<cite>` is dropped from context field

### ISSUE THREAD

**Issue by sydb** [projectEndings/staticSearch#305]
[This may be a bug. At least, I do not _think_ it is the result of a mistake I have made, but I have been wrong about that before. :-]

The content of `<html:cite>` is dropped from the context created for each search term.

To reproduce:

1. Download & expand 1.4.7.
2. Add file cite_me_not.html to the test/ directory (file can be found in the appendix of this post).
3. Issue `ant`.
4. Issue `fgrep -h 'situational' test/ssTest/stems/*` (or otherwise look at the results), and you will notice that the word “citation” does not occur in the output "context": field (it should be in that space before the comma).
5. Issue `cat test/ssTest/stems/citat*`, and notice that the word “citation” has no context around it.

**Appendix** — cite_me_not.html
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Theft 000382</title>
      <meta name="article type" class="staticSearch_desc" content="test" />
      <meta name="date of publication" class="staticSearch_date" content="2024-05-20" />
      <meta name="volume" class="staticSearch_num" content="18" />
      <meta name="issue" class="staticSearch_num" content="5" />
      <meta name="docTitle" class="staticSearch_docTitle" content="Theft 000382" />
      <script type="text/javascript" src="../../../uvepss/ssHighlight.js"></script>
   </head>
   <body>
     <div id="mainContent">
       This is a division with one firm
       <a href="https://bauman.zapto.org/~syd/temp/pics/some_nice_shots_with_50_mm/index.html">anchor</a>,
       one situational <cite>citation</cite>, one empirically
       <em>emphatic</em> phrase, and <span>22.86 cm</span> worth
       of nonsense.
       <p>
         This is a paragraph with a second firm
         <a href="https://bauman.zapto.org/~syd/temp/pics/2024-04-11_car_fire_4_press/index.html">anchor</a>,
         another situational <cite>citation</cite>, an even more empirically
         <em>emphatic</em> phrase, and <span>⅛ fathom</span> worth
         of nonsense.
       </p>
     </div>
   </body>
</html>
~~~

**Comment by joeytakeda** [comment]
Hi @sydb  — the test config file (e.g. `configTest.xml`) defines `<cite>` as its own context and so it is excluded from the flow of surrounding contexts (and should yield exactly what you get).

Does your configuration file also have `//context[@match='cite']` (e.g. line 42 of the configTest file)?

https://github.com/projectEndings/staticSearch/blob/bdb07a858974079c3ecf866cdf5c32e0d2e94047/configTest.xml#L42

If so, does removing that resolve the issue?

**Comment by sydb** [comment]
Thank you for the prompt reply, @joeytakeda.
So (of course) you are right, that line 42 of configTest.xml causes the `<cite>` behavior above, and commenting it out “fixes” it.
But what is mysterious (to me, at least) is that the config.xml I was using when I first encountered this does _not_ have any `<ss:context>` that matches `<html:cite>`, at least not directly. (The only line that matches the string “cite” is `<context label="works cited" match="div[ @id eq 'worksCited']"/>`.) I will have to poke around a bit to see if there is any other context my cite elements might be matching. Static Search only reads the one config file, right? (It doesn’t _also_ read configTest.xml or something, does it? Are there any built-in default contexts?)

**Comment by martindholmes** [comment]
@sydb staticSearch only uses one config file, so if it's behaving as though it's reading the test config instead of your config, then it must be doing that, for some reason.

**Comment by martindholmes** [comment]
@sydb A bit more info on this:

https://endings.uvic.ca/staticSearch/docs/howDoIUseIt.html#specifyingContexts

There are default contexts built into the indexing process, based on the most common HTML block elements, which are listed there. But it's not actually complete, so I'm going to update it; the complete list, as it appears on xsl/tokenize.xsl right now, is this:

~~~~~
body | div | blockquote | p | li | section | article | nav | h1 | h2 | h3 | h4 | h5 | h6 | td | details | summary | table/caption
~~~~~

But it definitely doesn't include cite.

**Comment by martindholmes** [comment]
@sydb Any reason to keep this open? Is there actually a bug?

**Comment by martindholmes** [comment]
@sydb Final ping before we close this ticket -- is there anything to do here?

**Comment by sydb** [comment]
Dunno. I will try to reproduce again.

**Comment by sydb** [comment]
So there are two things I plan to try to reproduce here. First, if I can reproduce the original problem, and second if the little test I suggested in the original post behaves as expected.

I decided to do the 2nd one first (just because I was being lazy, and it is easier). The results jarred me a bit:
1. Downloaded 1.4.7 to /tmp/
2. `cd /tmp/`
3. `tar xzf staticSearch-1.4.7.tar.gz && cd staticSearch-1.4.7`
4. `ant`

This leaves me with (among other things) a new directory at ./test/ssTest/. Being the curious sort, I looked to what was in it, only to find that 4 of the 13 items therein had quite bizarre names:
~~~
$ cd test/ssTest/ && ls -1F
'config_fatal:_not_a_git_repository_(or_any_of_the_parent_directories):_.git.json'
filters/
ssHighlight.js
ssInitialize.js
ssReports.css
ssSearch-debug.js
ssSearch.css
ssSearch.js
'ssStopwords_fatal:_not_a_git_repository_(or_any_of_the_parent_directories):_.git.json'
'ssTitles_fatal:_not_a_git_repository_(or_any_of_the_parent_directories):_.git.json'
'ssWordString_fatal:_not_a_git_repository_(or_any_of_the_parent_directories):_.git.txt'
staticSearch_report.html
stems/
~~~
Turns out all the files in stems/ and filters/ also have that bizarre name. Looks to me like it comes from the (newly created) file ./test/VERSION.

I am going to go back to testing the `<cite>`-is-dropped issue now, but I thought you might want to know about this VERSION-not-getting-created-properly problem first. (A problem I strongly suspect would not be present if I were to checkout the repo from git. I had rather downloaded it from the release page.)

**Comment by sydb** [comment]
Well, the little test above reproduced as expected — by default the test fails, citations are dropped, but when line 42 of configTest.xml is commented out, citations reappear. Yay!

The larger test that led me to this, however, does not reproduce — that is, there is no obvious major problem with the content of `<cite>` at first glance. I cannot explain what happened months ago to cause this and thus for me to open this ticket, but I think for now (as soon as you solve the VERSION-name-has-git-error problem, above) this ticket can be closed.

**Comment by martindholmes** [comment]
I've had one other report of those weird git-related files appearing so this is definitely a bug we want to nail down. I don't think it's happening in dev, but I'll test.

**Comment by martindholmes** [comment]
Now I understand it! To get the version string for the build, we run

git rev-parse --short HEAD

which assumes you cloned the repo; if you just downloaded the source, that doesn't happen. This should be an easy fix. We need to do it in dev and also in release 1.4.

**Comment by martindholmes** [comment]
I've created a PR for the fix in dev, and pushed a similar fix directly to the 1.4 branch; I'll do a 1.4.8 release if @joeytakeda is OK with the fix.

**Comment by sydb** [comment]
Excellent!
Can we close this now?

**Comment by martindholmes** [comment]
Thanks @sydb. Closing now.
