### ISSUE TITLE
Schema search path only works inside staticSearch repo

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#31]
The create_config_xsl.xsl file needs to interrogate the schema to find out the datatypes of various elements. It does this by finding the schema like this:

~~~~~
<xsl:variable name="schema" select="
        if (doc-available(concat($ssBaseDir, '/schema/staticSearch.odd'))) 
        then document(concat($ssBaseDir,'/schema/staticSearch.odd'))
        else document('https://raw.githubusercontent.com/projectEndings/staticSearch/master/schema/staticSearch.odd')"
        as="document-node()"/>
~~~~~

This works if the current build process is running inside the staticSearch repo structure, but when it's called from outside, it fails to find the local copy, meaning that the validation fails because it pulls an old version of the schema from the master branch. I'm not sure why it's failing, but it may just be that ssBaseDir is too loosely-configured.

**Comment by martindholmes** [comment]
I've tested this in a scenario where the build is run from inside the staticSearch repo and the config file and materials are elsewhere, and where the build is run from where the materials are and the staticSearch repo is elsewhere. As long as full paths are provided at the command line, it seems to work fine. However, if the fallback of going to the web for the ODD file is retained, it will have to be made version-controlled; it's no good getting an ODD file from the master branch or the dev branch if the codebase you're using is actually from a release tag. I'd like to suggest that we have a VERSION file which by default contains nothing, but when you're about to do a release tag, you set it to contain that tag, and the XSL then reads that to discover where to get its external ODD from.

In the meantime, I'm moving the milestone for this to 0.8, because I think as long as our documentation is clear about using full paths, the remote retrieval should be unnecessary.

**Comment by joeytakeda** [comment]
In https://github.com/projectEndings/staticSearch/commit/6a4d903b3539fa8ec95fd4305e14858b8cf20e60 I have attempted to resolve this issue. I've taken a more (perhaps overly) cautious approach than what @martindholmes suggests above. 

I've split the variable into two-- $schemaURI and $schema--just for ease of messaging. The schema URI process is as follows:

1. Check to see if the staticSearch.odd is available locally in the repo. If so, use that URI
1. Check to see if a VERSION.txt can be found locally (the name VERSION.txt is what is current in v0.7); if so, then take the first line of VERSION.txt, put it in the URL, and get the thing from Github at that version.
1. If VERSION.txt does not exist, then use the Github API to find the latest release. Use that version number and download the ODD file from that version.
1. If, for whatever reason, that doesn't work, then get the ODD from the /dev/ branch.

How does that look to you, @martindholmes ?

**Comment by martindholmes** [comment]
Looks really good -- I'll test later today!

**Comment by martindholmes** [comment]
I think this is fine -- forgot to close it before.
