### ISSUE TITLE
Kwics in search results should be sequenced in document order

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#32]
Right now, the sequence of keyword-in-context strings you see when you do a search is an accidental result of the order in which the terms are searched. It would make much more sense to provide the kwics in document order. To do this:

1. Add to the indexing a position indicator for each kwic, in as compressed a way as possible (e.g. `"p": 25"`).

2. Update the ResultSet object in the JS to make it sort kwics by these values before displaying them.

**Comment by joeytakeda** [comment]
An approach for the XSLT:

Run a template, after tokenization, that assigns numbers to each `<span>`. We could use preceding axis, but that would end up being a processing hog, so I think we should take advantage of accumulators:

```
    <xsl:accumulator name="stem-position" initial-value="0">
        <xsl:accumulator-rule match="span[@data-staticSearch-stem]">
            <xsl:value-of select="$value + 1"/>
        </xsl:accumulator-rule>
    </xsl:accumulator>
    
    
    <xsl:template match="span[@data-staticSearch-stem]" mode="enumerate">
        <xsl:copy>
            <xsl:attribute name="data-staticSearch-pos" select="accumulator-before('stem-position')"/>
            <xsl:apply-templates select="@*|node()" mode="#current"/>
        </xsl:copy>
    </xsl:template>
```

The KWIC harvesting in `json.xml` will be straightforward then.

**Comment by martindholmes** [comment]
Looks perfect. I don't think that will add much time to indexing.

**Comment by joeytakeda** [comment]
Done in commit https://github.com/projectEndings/staticSearch/commit/f8716c33331659f9f6ddccecb013cbdc1989387b 

I've called the field "pos" in the JSON and not "p" for consistency's sake: in the JSON we call everything else by a fairly long name ("contexts", "context", etc), so I think calling it "pos" does more good in terms of readability than bad in terms of file size.

**Comment by martindholmes** [comment]
Makes sense. Assuming the web server zips the files, it'll make virtually no difference to the transmission size, I don't think.

**Comment by martindholmes** [comment]
JS is now sorting kwic results in document order. I'm assuming we don't want to further complicate the process by trying to prioritize MUST_CONTAINs or phrasal searches over other components; assuming we're going to let users expand the kwic list to see all hits anyway, I think that would be excessively complicated.

**Comment by martindholmes** [comment]
I think this is now working, so I'm closing it.
