### ISSUE TITLE
Add Moravians at Sea to list of projects using staticSearch 

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#325]
Per @mprell 's comment here https://github.com/projectEndings/staticSearch/discussions/237#discussioncomment-11216130, we should add the The Moravians at Sea project to to our list of known examples: 

Search site: https://www.moravians-at-sea.de/suche.html
Data and configuration file etc.: https://github.com/mprell/moravians-at-sea-Prod

**Comment by martindholmes** [comment]
Done in dev and release-1.4 branches. Added a couple of other new sites too.
