### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#33]
Of course it does. The first error is a path error:

~~~~~
config:
     [java] Creating configuration file from Z:\staticSearch/configTest.xml
     [java] ERROR: Config file Z:\staticSearch/configTest.xml not found.
     [java] Error evaluating (if(fn:doc-available(...)) then ... else ...) on line 64 column 46 of create_config_xsl.xsl:
     [java]   XTMM9000: Processing terminated by xsl:message at line 64 in create_config_xsl.xsl
     [java] at procedure configDoc on line 58 of create_config_xsl.xsl:
     [java]      invoked by global xsl:variable
     [java] at procedure versionDocUri on line 112 of create_config_xsl.xsl:
     [java]      invoked by global xsl:variable
     [java] at procedure versionString on line 118 of create_config_xsl.xsl:
     [java]      invoked by global xsl:variable
     [java]   In template rule with match="/" on line 212 of create_config_xsl.xsl
     [java] Processing terminated by xsl:message at line 64 in create_config_xsl.xsl
~~~~~

This is the usual backslash versus slash issue, I think; `<property name="configFile" value="${basedir}/${config}"/>` in build.xml is mixing a system path and a URI.

**Comment by martindholmes** [comment]
@tklampfl reports:

The tokenize step fails with the error message:

>     [java] Error in xsl:result-document/@href on line 164 column 64 of tokenize.xsl:
>     [java]   XTDE1490  Cannot write more than one result document to the same URI:
>     [java]   file:/temp/dita-example-2/out/xhtml/search/temp/_tokenized.html
>     [java]      invoked by xsl:for-each at file:/C:/Temp/staticSearch/xsl/tokenize.xsl#95
>     [java]   In template rule with match="/" on line 91 of tokenize.xsl
>     [java] Cannot write more than one result document to the same URI: file:/temp/dita-example-2/out/xhtml/search/temp/_tokenized.html

The problem seems to be following line in ```tokenize.xsl```:

<xsl:variable name="relativeUri" select="substring-after($uri,$collectionDir) => replace('^(/|\\)','')" as="xs:string"/>
The value of ```$uri``` is ```file:/C:/temp/dita-example-2/out/xhtml/1890-05-22_01.html```
The value of ```$collectionDir``` is ```file:/temp/dita-example-2/out/xhtml```
The ```substring-after()``` delivers an empty string. Therefore the filename is always the same.

If you need further information do not hesitate to contact me.
Thank you for your help and your project.

**Comment by joeytakeda** [comment]
Here's a thought: what about creating a docker container for staticSearch so that if people are using Windows, they could just use that? I've only had limited experience with Docker, though, so maybe I'm thinking about this the wrong way....

**Comment by martindholmes** [comment]
That might work, except that someone's project build process would have to be completely transferred into the docker container, or the docker container would have to be configured to mount specific folders from their project build in order to work properly, and that's not really trivial. I think anyone that needs a working Windows build needs it because they're not capable of (for instance) installing and configuring the Windows Subsystem for Linux; if that's the case, installing and configuring Docker isn't going to be easy for them either.

I think really if we want to support Windows, it's up to us to rewrite our ant and XSLT code to be platform-neutral. But I would also be OK with abandoning the idea of supporting Windows entirely if it's just going to cost us too much time and effort.

**Comment by martindholmes** [comment]
Adding extra wrinkles from @lyallg's issue #77, which merges with this one:

List of reserved windows filenames:

CON, PRN, AUX, NUL
COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

If files called e.g. "con.json" are created, they can't be deleted by an ordinary user. No idea what we might do here, other than add these things to the stopword list if you're building on Windows.

**Comment by martindholmes** [comment]
I'm punting this to 1.2 because it requires testing on a Windows machine, and the only usable Win 10 vm I have is at work, which is not accessible over the next couple of weeks.

**Comment by martindholmes** [comment]
We do have to get to this, but at the moment it's low-priority. Setting to Blue Sky.

**Comment by joeytakeda** [comment]
Thanks to #250, this seems to be *mostly* fixed, but we still have the issue of the reserved file names. Will make a new ticket for that to keep it near the top and will close this one.
