### ISSUE TITLE
Stemming support for Early Modern English

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#35]
This ticket is a place where we can gradually assemble info and create the plan to add support for Early Modern English to the stemmer. This involves one of two approaches: either a preprocessor that attempts to convert EME into ME before the regular Porter2 English Stemmer implementations do their work, or a set of new rules integrated into the stemmer. My preference is for the former if that's practical, because it makes for a clean separation.

There's a cursory approach to this on the Snowball site:
http://snowball.tartarus.org/texts/earlyenglish.html
but it handles only -est and -eth endings, which is a small subset of what we need to deal with. This is the beginning of a list, in no particular order, based on looking at some of the Mayoral Shows on the Map of Early Modern London:

* Long s (just replace with regular s).
* Thorn, wynne and eth (again, just replace with their modern equivalents).
* Various ligatures (just expand to normal versions).
* vv for w (just replace).
* v for u, and vice versa (v between consonants can be replaced with u; word-initial u followed by a vowel can be replaced).
* i for j, and vice versa (similar options as above).
* -ie for -y endings such as "historie" (probably we can just replace on all polysyllabic words).
* -es for 's in possessives such as "last yeeres discourse".
* -es for -s in plurals such as "lockes". Obviously it is impossible to mechanically distinguish between this and the possessive, but since the result would be stemmed, that doesn't matter.
* Trailing -e, as in "firme", "wee", "doe".
* 2nd person singular -est, and associated consonant-doubling (sittest).
* 3rd person singular -eth, and doubling (sitteth).
* Doubled final consonants, as in "triumphall", "powerfull".
* Doubled final consonants with additional -e, as in "sinne".

And of course the kicker, to which I can think of no easy solution: random variant spellings. We can have mappings for common ones, such as yeer and neer. We'll also need to add a range of historical forms such as "thou", "art", "wert" and so on to the stop list. 

One approach might be to try to acquire the word list from here:
https://leme.library.utoronto.ca/search/word
and map it to modern equivalents.

**Comment by joeytakeda** [comment]
Does the early modern stemming apply also to the search process itself? I.e. are we handling cases where someone is looking up an early modern word or do we assume that all search queries are in the modern English?

**Comment by joeytakeda** [comment]
I've started to lay out very basic groundwork for this. No changes to the stemming code, but I've downloaded and added MoEML's shows to the repo (and the XSLT I used to generate them) and set up a bare-bones config to get this up and running.

**Comment by joeytakeda** [comment]
> One approach might be to try to acquire the word list from here:
> https://leme.library.utoronto.ca/search/word
> and map it to modern equivalents.

You can download the lexicon plaintext files here: https://leme.library.utoronto.ca/lexicons?DI. They're XML-ish, but not well-formed (duplicate attributes, for instance).

**Comment by martindholmes** [comment]
@joeytakeda Switched this from the 1.1 milestone to the 1.2 milestone, since we still don't have a clear plan for it. Switch it back if you disagree.

**Comment by martindholmes** [comment]
Stemmers are now pluggable, so we think this would be unwise use of our time; projects could implement this if they need it, so closing with wontfix.
