### ISSUE TITLE
Need documentation for creating search page

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#36]
We have no documentation yet for how to create a shell search page, what the div should be id'd, et cetera.

I also have a vague recollection that we were going to build the search page creation in such a way that if you do not provide a `search.html`, then we would create one for you. Is that something we still wanted to do or should we make it mandatory that users must create a shell search page?

**Comment by martindholmes** [comment]
Maybe we should have a generation function that will create one for you and put it at the place you specify in the config. That would get you started, and you could then customize it to match your site.

**Comment by martindholmes** [comment]
Documentation added in https://github.com/projectEndings/staticSearch/commit/52f04991164bf2e543a3ef5bff0d44647e37c121. I'll raise a fresh FR ticket for the possibility of a page-generator feature.
