### ISSUE TITLE
Build tests broken due to /ssTest/ directory

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#37]
Since 890f6a20859daa6bbffea9cad0bb344b02bbf156 the build tests have been broken due to the Static Search report for the directory /ssTest/ being indexed. 

![Screen Shot 2020-01-18 at 8 25 35 PM](https://user-images.githubusercontent.com/17664763/72674847-b94e9e80-3a30-11ea-982a-a6e40636289a.png)

This is from build 54. But I can't see the /ssTest/ directory anywhere in the Git repo. Maybe this is a case of Jenkins archiving things it shouldn't--I don't have permission on the Jenkins job, but this might be simply solved by refreshing the workspace?

**Comment by martindholmes** [comment]
The test config specifies ssTest as the output folder instead of the staticSearch default, as a way of testing configurable output folders. But the output folder should be deleted at the beginning of the build process, so the report shouldn't be there to index. So I think this is a genuine issue. I'll check into it.

**Comment by martindholmes** [comment]
Definitely not broken for me locally. I've wiped out the Jinks workspace and we'll see if that fixes it.

**Comment by martindholmes** [comment]
Working fine now. Closing.

**Comment by martindholmes** [comment]
Although now I think about it, there is an issue here, so I'm re-opening. If you have two different indexing processes running on the same collection, the second one that runs will find and index the search report for the first one. So we need to make sure the indexing process ignores our own indexing reports.

**Comment by joeytakeda** [comment]
If we go for the data-staticSearch-ignore=true approach for ignoring elements, we could just generate the report with that attribute on the HTML element by default

**Comment by martindholmes** [comment]
Fixed in commit b83f7f1. We should still consider the data-ssIgnore="true" approach for other reasons, but for now we avoid indexing anything with the filename used for the build report (which is also now a parameter).
