### ISSUE TITLE
build fails on master branch and v0.7 release

### ISSUE THREAD

**Issue by wsalesky** [projectEndings/staticSearch#38]
I downloaded both the master branch from github and the v0.7 and have been unable to build the test project successfully. 

Error: 
```
BUILD FAILED
/Users/..../staticSearch-0.7/build.xml:51: Problem: failed to create task or type if
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

Total time: 0 seconds
```
Running on a MacOS Catalina. 
 
I have both Java and Ant installed and have run ant on other projects successfully. Any pointers on how I can get the project to build? I'm very interested in working with this code on an upcoming TEI project I am working with. Thanks for the help.

**Comment by martindholmes** [comment]
You'll need ant-contrib installed as well. Sorry, that should be in our documentation!

**Comment by wsalesky** [comment]
That worked! Thanks for the swift reply, I'm looking forward to playing around with this project.

**Comment by martindholmes** [comment]
I'm going to re-open this because we need to add this to our documentation. Thanks for prompting us!
