### ISSUE TITLE
Create an ant task that will auto-generate your search page

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#39]
Following on from issue #36, I think we should actually build a rudimentary search page in your output folder if the path you specify for your search page is not there, but the rest of your HTML document collection is there and is well-formed. So for a fresh user, the process would go:

1. Specify the filename of a search page that doesn't yet exist, but is in the folder where your documents are.
2. Run the search build, and get a rudimentary page that works.
3. Customize that page as you like, avoiding removing the essential container div.
4. Whenever you rebuild, the customized version will be used.

**Comment by joeytakeda** [comment]
What about having a template one that can serve as both an example and as the sample one? That is, we make a "sample_search.html" or something in the documentation directory. If we can't find a search page where you say your search is, we'll just take sample_search.html and copy it to the destination you specified.

**Comment by martindholmes** [comment]
Much better and simpler. Good call.
