### ISSUE TITLE
FR: New filter type: numeric

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#45]
We should have the ability to search for a numeric range (between X and Y) in the dataset. I think we should handle all numbers (i.e. xs:decimal). That excludes having scientific notation, but I think that should be fine.

The first step is to add it into the JSON files, which won't be trivial, but should be straightforward. I think the structure to be like the the dates filter (i.e. organize by docs with the numbers as values). 

We will need to do a sanity check on the input data, though, to make sure that if you say something is a number it actually is.

The second step is to add the handling to the Javascript.

The third step is to add it to the search page; I think we'll want to have two `<input type="number">` with a display similar to how we have dates so that people can specify a min value and a max value.

**Comment by martindholmes** [comment]
We might also use an input range element (slider), although determining the step value might be slightly tricky.

**Comment by joeytakeda** [comment]
The issue with the range slider is that it only lets you pick one value in the range, rather than between a range within the range, as far as I can tell: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by martindholmes** [comment]
You'd need two sliders, of course, just as you would need to number inputs.

**Comment by joeytakeda** [comment]
Right, of course. I was also thinking that there was an input type="number", which there isn't, so that makes sense to me.

**Comment by martindholmes** [comment]
There is an input type="number", and I'm not absolutely sure that it's the wrong thing to use; some people like sliders and others would rather type something in.

**Comment by joeytakeda** [comment]
I think all the handling in terms of the XSLT and JSON creation for the `staticSearch.num` should be in place. I haven't added it to the search page yet, though.

**Comment by joeytakeda** [comment]
I now have it in the search page with a display similar to the dates (though, determining min and max values was infinitely more straightforward than dates :-)). 

I've done `<input type="number">` for now; if we use the range, I think we'd need to add some extra handling to show the value that is being chosen by the range slider.

**Comment by martindholmes** [comment]
That was quick! I'll try to get to the JS this week, but don't hold your breath...

**Comment by martindholmes** [comment]
Got the JS done, and added a couple of tweaks to the search page stuff. Also added a test which uses it.
