### ISSUE TITLE
Combined scores not sorting properly in Chrome

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#46]
In Chrome (80.0.3987.122) the results aren't sorting by score properly when you have two or more search tokens. I think this has been broken for a little bit at least, since the results are consistently wrong with the new codebase and an older version.

Searching for the string "include elephants" (no quotations) in the static search test in Chrome yields:

> Test home page Score: 3
> ...variety of scenarios the codebase needs to handle, including:
> ...percentages such as 73.58%. One of the poems includes the phrase summer day—our day, and if...
> ...and in one other document, but it is included in the test stopwords list so it...
> badthings Score: 11
> ...file has a number of bad, ignominious features, including the fact that it has no title,...
> ...and is generally not worth reading. It also elephant has the word elephant three elephant times....
> ...worth reading. It also elephant has the word elephant three elephant times.
> Alcohol on Vancouver Island Score: 2
> ...new, British Colonies, presents very deplorable results.Which may include pink elephant hallucinations, especially in 1870. The...
> ...Colonies, presents very deplorable results.Which may include pink elephant hallucinations, especially in 1870. The following figures...

But in Firefox it does:

>     badthings Score: 11
>         ...file has a number of bad, ignominious features, including the fact that it has no title,...
>         ...and is generally not worth reading. It also elephant has the word elephant three elephant times....
>         ...worth reading. It also elephant has the word elephant three elephant times.
>     Test home page Score: 3
>         ...variety of scenarios the codebase needs to handle, including:
>         ...percentages such as 73.58%. One of the poems includes the phrase summer day—our day, and if...
>         ...and in one other document, but it is included in the test stopwords list so it...
>     Alcohol on Vancouver Island Score: 2
>         ...new, British Colonies, presents very deplorable results.Which may include pink elephant hallucinations, especially in 1870. The...
>         ...Colonies, presents very deplorable results.Which may include pink elephant hallucinations, especially in 1870. The following figures...

And in Keats doing "hazlitt poem" is similarly off:

http://johnkeats.uvic.ca/search.html?q=hazlitt%20poem

In Chrome, I get this as the first result:

> 22 October 1818: Walking With Hazlitt, Thinking Like Hazlitt, Not Playing Racquets Like Hazlitt Score: 38

In Firefox and Safari, I get:

> Select Chronology & Keats’s Key Comments: 1817: 1817-03 Score: 45

**Comment by martindholmes** [comment]
Confirmed on Linux with Chromium too. Will fix when I have a chance. This is our first experience on this project of JavaScript running behaving differently across browsers, I think. :-(

**Comment by martindholmes** [comment]
Had a go at a fix in commit #fabec43. No time to test thoroughly, but it seems to work locally for the test set.

**Comment by joeytakeda** [comment]
Thanks, Martin! I'll get all the projects for which I have the ability to trigger a rebuild to rebuild and then test with those.

**Comment by joeytakeda** [comment]
Tested on WEA and LOI in Chrome, Firefox, and Safari, and everything looks good. Closing now.
