### ISSUE TITLE
Filter-only results should be sorted in some way

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#51]
Presumably alphabetical; do we strip off leading article before sorting, or is that overkill?

**Comment by joeytakeda** [comment]
I think a crude alphabetical ordering is perfectly fine--in future, we might want to provide other mechanisms for sorting (by date or something), but I don't really think that's worthwhile at this point :-).

**Comment by martindholmes** [comment]
I've had a specific request for sorting by date, for the Despatches project. But now I think about it, I'm not sure how it could be implemented; the results information doesn't have any data about filters in it. The only approach I can imagine would be this:

 - When compiling the results
 - For each result document
 - Visit each filter set that's active for the search
 - Add any filter information applying to that document
 - Express the results as a table

Obvious problems would arise for desc filters for which multiple tokens may apply -- does each token get a separate column? And this could result in dozens of columns for a sophisticated search.

The other option is that we make date filters a special case, and always bundle only date filters into the results. But are they a special case? 

Or is this a case where a project should override some methods to provide their own processing?

**Comment by joeytakeda** [comment]
I think this is a per project thing since date might not be generalizable; it's probably better to have some examples—or even "recipes"—of how people can override these display options and keep the base functionality as simple as possible.

**Comment by martindholmes** [comment]
I'm shifting this to the 1.1 milestone because it's not yet clear how we can proceed on it. I have been wondering whether documents themselves should have a sort key of some kind, configured in a meta tag, and propagated into the ssTitles_xxx.json file.

**Comment by martindholmes** [comment]
Since I have a need for a straightforward implementation of this in the next Despatches release, I'm going to go ahead with the simplest possible version: a meta tag with `@name="ssDocSortKey" value="thesortkey"`, harvested into the ssTitles*.json file and used by the SSResultSet object as a secondary sort key where there are hit scores, and the primary sort key where there aren't. We can easily implement something cleverer that's end-user-controlled based on filters later; the two ideas don't conflict with each other, since one's a pre-configured default sort order provided by the site designer, and the other would be an automated set of controls for the user to manipulate.

**Comment by joeytakeda** [comment]
Sounds good to me! The only small adjustment I'd suggest is that, rather than use a new meta, we could just hook it on to the pre-existing `ssDocTitle` meta tag. So something like:

```
<meta name="ssDocTitle" value="My Custom Title" data-sstitlesortkey="200_title"/>
```

That just seems slightly cleaner: if we aren't sorting by score, we're sorting by title and so it makes sense for the sort key to be on the title; that would also mirror the filter sort key encoding (`@data-ssfiltersortkey`) so that, if we do end up implementing #86, we have a single type of encoding for adding sortable metadata.

**Comment by martindholmes** [comment]
I thought about using the ssDocTitle thing, but the problem is that most projects won't use that meta tag at all; adding it in order to allow the sort key will force people to generate a custom doc title, which will inevitably be the same as the main doc title -- or if it's not, will result in confusion. So I think these are two distinct things, to be honest.

**Comment by martindholmes** [comment]
The Despatches project pages should now -- assuming Mr Jenkins cooperates -- all be equipped with ssDocTitle meta tags, ready for testing. I'll create a branch for this work, hoping the current proliferation of feature branches doesn't cause merge problems later.

**Comment by martindholmes** [comment]
Finished and tested initial implementation in branch issue-51-docSortKey. I'll do more testing in this branch using the Despatches project, and then if all is well, create a pull request.

**Comment by martindholmes** [comment]
This has now landed in dev and can be closed.
