### ISSUE TITLE
Add a Projects section to the documentation

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#53]
We should consider add a projects that use Static Search to the Documentation section to show it live and in action. Maybe a list or a table?

**Comment by martindholmes** [comment]
Good idea. We have DVPP and Keats live already; I don't think we should point anything at a Jenkins build, though. MyNDIR will be live in the next few months, and ditto MoEML I hope. Is there a plan for a permanent home for WEA?

**Comment by joeytakeda** [comment]
Yes there is a permanent home for the WEA: https://winnifredeatonarchive.org (currently password protected but should be open in the next couple weeks). Do we want to add this before the first release (not really a major change) or do we want to wait?

**Comment by martindholmes** [comment]
We're still a little way out from release, so let's create the page but leave this ticket open so we can add WEA if it's live by the time we release.

**Comment by martindholmes** [comment]
Once Pull request #81 has been merged, we can address this, since WEA is now live.
