### ISSUE TITLE
Beginning with version 1, we shouid use semantic versioning

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#54]
The TEI is adopting semantic versioning:

https://semver.org/

and I think we should do the same, starting with version 1.0.x. The issue for us perhaps is going to be figuring out what an "API change" might be in the context of our project; is this any change which  would require that a user change existing config XML files? Or is it anything that would change the functionality of any existing search system even without a change to its config? Or both?

**Comment by martindholmes** [comment]
What this would require:

1. A VERSION file in the root of the repo. Question: If we're working in a branch, and that branch work will change the version number, do we update the VERSION file in the branch?

2. The VERSION file would include Major.Minor.Patch info, but also -alpha or -beta.

3. Appropriate packaging/labelling in the build process, presumably also carrying into the documentation, would (for some contexts anyway) automatically append the date and the current short git commit hash, with a +,  so we would get 1.1.0-alpha+2020-09-30.086835a.

4. Since we're now working towards a 1.0 release, I believe our current version file should contain 1.0.0-alpha.

@joeytakeda Any thoughts?

**Comment by joeytakeda** [comment]
> A VERSION file in the root of the repo. Question: If we're working in a branch, and that branch work will change the version number, do we update the VERSION file in the branch?

I don't think the branch work should affect the version file. In my mind, the version should always be bumped after a commit to the master branch, right (i.e. each version is mapped to a release). So as soon as we release 1.0.0-alpha, we bump the VERSION file to 1.0.0-beta (or whatever) and all of the work in branches etc work from that version without changing the version number. 

> Appropriate packaging/labelling in the build process, presumably also carrying into the documentation, would (for some contexts anyway) automatically append the date and the current short git commit hash, with a +, so we would get 1.1.0-alpha+2020-09-30.086835a.

Are both date and commit hash necessary? I would think that the commit hash is easily referenceable to a date (but of course it doesn't _really_ matter since it's just a version string).

> Since we're now working towards a 1.0 release, I believe our current version file should contain 1.0.0-alpha.

Agreed.

**Comment by martindholmes** [comment]
Your comment raises an issue: Do we ever release alphas or betas through the master (which should presumably be main) branch? I wouldn't have thought so; I'd rather keep that branch for long-term stable releases. If we do release alphas and betas, presumably that would be for other users to test, and we might release them in a different way.

Re date and hash: since hashes give you no notion of how old something might be, I think we do need the date so that humans can easily tell whether a specific package is recent or not. Also, as long as we have both of those, then we can build multiple packages even on the same day with the same designation (1.1.0-alpha) and they would still be differentiated by the version string, which is important. We wouldn't have to get into alpha.1, alpha.2, etc., which will be confusing.

**Comment by martindholmes** [comment]
I've gone for a file called EDITION in the root of the repo. The main reason for EDITION rather than VERSION is that we create and use VERSION files for search project builds, and they're consequently in our .gitignore; makes sense to use a different filename for the software versioning, and EDITION is consonant with Endings terminology. It's not being used for anything yet.

**Comment by joeytakeda** [comment]
Sorry I dropped the ball on this! EDITION sounds good to me.

> Your comment raises an issue: Do we ever release alphas or betas through the master (which should presumably be main) branch? I wouldn't have thought so; I'd rather keep that branch for long-term stable releases. If we do release alphas and betas, presumably that would be for other users to test, and we might release them in a different way.

I would argue that a change in the EDITION file would warrant a Release, but releases could just be done from the `dev` branch and not the master one, reserving releases on the master branch to fully formed releases (1.0.0). 

> Re date and hash: since hashes give you no notion of how old something might be, I think we do need the date so that humans can easily tell whether a specific package is recent or not. Also, as long as we have both of those, then we can build multiple packages even on the same day with the same designation (1.1.0-alpha) and they would still be differentiated by the version string, which is important. We wouldn't have to get into alpha.1, alpha.2, etc., which will be confusing.

That makes the release name really unwieldy, but we could always just do that for the actual assets zipped in the release.

So release 1.0.0-alpha has assets named like:

```
1.0.0-alpha+2020-09-22.08af0cd2.zip
```

**Comment by martindholmes** [comment]
I've done a bit of work here -- can you test ant -f makeRelease.xml? I think it's doing everything right.

**Comment by joeytakeda** [comment]
The EDITION and git hash stuff worked, but I noticed that we hadn't updated the makeRelease file to account for the `/stemmers/` directory, so it wasn't being copied over. That's done now in f924916

**Comment by martindholmes** [comment]
Ah, good catch. I never thought about that. Any reason not to close this now?

**Comment by joeytakeda** [comment]
Nope! Looks good to me! Closing now
