### ISSUE TITLE
Making the search button more accessible

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#55]
In search pages with lots of filters, by the time you've worked your way down to the bottom of all the filters, you can't see the search button any more. I've had a suggestion that a second button be provided at the bottom, but I'm wondering whether it might make more sense for the search button and the clear button to be position:fixed somewhere, perhaps on the right of the screen, so they're always available. That might look a little weird, since they'd still be there when you were scrolling through search results, so perhaps an approach with position: sticky would be better.

**Comment by martindholmes** [comment]
Having hacked around a bit with position: sticky, I don't think it can be used in our context, because we have nested flex containers. Perhaps a cloned button is the thing to do. It could be an option in the config, or it could be done automatically based on some threshold number of filters.

**Comment by joeytakeda** [comment]
Hmm. I'm not sure--I think it depends on how much we're concerned with providing the UI for the search button in some way that makes sense for us, or if we want that to be up to individual projects? I think we create something with the minimum one needs to make it work, but if they want extra things to spruce up the aesthetics, then I think it's a per project modification thing. I think if we make the standard search interface as simple as possible, it makes modifying it easier, which web designers are going to end up doing anyway.

**Comment by martindholmes** [comment]
So we'd suggest that they write JavaScript to clone that button, and try to make that happen at a point where it'll be successful? I'll have to do this for the Despatches, so we'll see how practical it turns out to be. But it's not unreasonable to provide two buttons if you ask for them, surely? It seems a simple thing, and likely to be useful to lots of projects.

**Comment by joeytakeda** [comment]
Fair enough. I'm in favour though of this being a completely opt-in thing only, so you have to explicitly set `<addSearchButtonAfterFilters>` to true for it to appear.

**Comment by martindholmes** [comment]
Absolutely; there's no reason for people to have it until their search gets to the size where they need it.

**Comment by martindholmes** [comment]
So, to summarize: have we decided that:

 - There should be a configuration item `<addSearchButtonAfterFilters>`.
 - If that's set to true, it should be passed on to the JS object.
 - If the JS object has it set to true, and some other metric determines it will be useful, it clones the search button.

If so, the question is what the metric might be. We could simply check whether the content height of the page is greater than the viewport height (before any search is run), so we know that there's a possibility that the first search button might scroll offscreen.

**Comment by joeytakeda** [comment]
I'm wondering if rather than making the button for people and trying to determine a metric for creating the thing (that inevitably won't work in some cases) and determining the ideal place for it (which again won't always work depending on how people style things), we just modify the JS so that if you have a button with, say, a class of "ssDoSearch" or whatever, then the JS knows to make that button actionable. That way, people can have as many buttons as they want and put them where ever they want.

**Comment by martindholmes** [comment]
The trouble with that would be that the button would most likely want to go into the div that we empty and overwrite as part of the build process, I think.

Maybe we should just always add a second button if there are any filters?

**Comment by martindholmes** [comment]
I think for the moment I'm just going to have the XSLT clone the search button if there are any filters at all. Let's see how that looks for our various sites. I'll give it an additional class so it can be hidden if required.

**Comment by martindholmes** [comment]
I've added a second search button whenever there are search filters, to appear below the filters, in commit 3bcb058. It has an id of ssSearchButton2, which can be used to target and hide it in CSS if required. Let's see how that looks.

**Comment by joeytakeda** [comment]
This looks good to me, but two queries:

1. Should the `<button>` be in a  `<span>` to be consistent with the rest of the buttons?
2. Should the `<button>`'s parent also have a `@class`? That would make it parallel with the rest of the structure.

So maybe something like:

```
<span class="postFilterSearchBtn">
<button id="ssDoSearch2">Search</button>
</span>
```

and then in the default CSS do:

```
.postFilterSearchBtn{
display:block;
}
```

**Comment by martindholmes** [comment]
That works for me. I have it in a div, otherwise it stretches the full width as a flex child. The span will do instead, I guess.

**Comment by martindholmes** [comment]
This is done. There's no need for the CSS as far as I can see, because the span's parent is display: flex.
