### ISSUE TITLE
Change `@xpath` to `@match` in config

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#57]
`@match` is a more descriptive name for the configuration functions, since rules, et cetera, all must follow the XSLT specification for `@match` and not `@xpath`. So we should rename all `@xpath` to `@match`.

**Comment by martindholmes** [comment]
I think this is done now, but we should have a good check through the documentation before closing.

**Comment by martindholmes** [comment]
I believe this is complete.
