### ISSUE TITLE
JS assumes all filter categories have members

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#62]
I created a boolean filter which was wrongly configured, and ended up with no documents in the "true" category. The result is a JS error because the code assumes there are always members. Error:

` Error attempting to generate the set of docs matching filters: TypeError: this.mapFilterData.get(...)[valueId] is undefined`

I think two things would be appropriate here:

 - The XSLT should still create a category in the JSON with an empty document array;
 - The JS should check for the presence of the category in the JSON before trying to read it.

**Comment by joeytakeda** [comment]
Sounds fine to me. I'd add one further thing: the XSLT should produce a WARNING message if there's a boolean configured with only a single member, since it doesn't really make any sense to have a boolean filter configured with only one of true or false.

**Comment by martindholmes** [comment]
Good point. When should it do that?

**Comment by martindholmes** [comment]
JS is fixed as of commit 3f8021e. I think I'm going to close this now because, after thinking about it, it's perfectly reasonable to have a true classification for some feature, where there are none which have false (or vice versa). Or perhaps better: it's reasonable to have a subset of your documents for which you feel confident in claiming X is true, whereas you don't feel confident in claiming it's false for any of the others. I will raise an enhancement ticket for the XSLT warning, but I don't think it's essential for the 1.0 milestone.
