### ISSUE TITLE
<input type="number"> only allows integers

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#66]
In the LOI project, the oral history search box allows users to search for interviews on their length in minutes. Here's an image before input where min is set to 4.47 minutes and max is set to 230.7 minutes:

![Screen Shot 2020-07-23 at 10 16 01 PM](https://user-images.githubusercontent.com/17664763/88362686-4f41e980-cd32-11ea-8acf-f056bd4d5517.png)

If you try to enter a range of 30 to 60, I get an input error:

![Screen Shot 2020-07-23 at 10 17 15 PM](https://user-images.githubusercontent.com/17664763/88362709-6a145e00-cd32-11ea-9da1-07ae76fa4ec8.png)

According to MDN, the `@step` attribute for `<input type="number"/>` has a default value of "1" (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step), meaning that non-integer values input values are invalid by default. That's not going to work in all cases, of course.

So, should we: try and be smart and determine a proper step by determining the the small step value (in this case, 0.01) or should we just set `@step` to `any` by default like so: `<input type="number" step="any"/>`?

**Comment by martindholmes** [comment]
What's the effect of step=any? Does that solve the problem without making things awkward for integer cases?

**Comment by joeytakeda** [comment]
It basically just lets you enter any number you want (within the min and max, of course), which I think is the desired behavior.

**Comment by martindholmes** [comment]
Go for it in dev, then, and let's see if the test projects all work OK.

**Comment by joeytakeda** [comment]
Tested on test set and it seems to work perfectly well. Building LOI now and will see how it works there.

**Comment by joeytakeda** [comment]
Works as expected on LOI and in the test set. I can't think of any other projects using numeric searches—can you, @martindholmes?

**Comment by martindholmes** [comment]
ColDesp used to but not any more.

**Comment by martindholmes** [comment]
@joeytakeda actually our test page uses it, but when I try it there, it seems to change its value when I run a search. Do you see the same odd behaviour?

**Comment by joeytakeda** [comment]
@martindholmes I don't see any odd behaviour in Firefox or Chrome--the number stays the same before and after the search.

**Comment by martindholmes** [comment]
Must be something to do with caching previous values then.

**Comment by joeytakeda** [comment]
@martindholmes This was working as far as my testing could tell—did we determine the issue that you were facing or is this still broken in some way?

**Comment by martindholmes** [comment]
Working as far as I can see now. Will close.
