### ISSUE TITLE
Need a mechanism for specifying that elements are completely ignored when indexing

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#74]
In a couple of different projects, I have a requirement to suppress entirely bits of text which must appear on the page but should not be part of the search index. For example, a wrapped-up line:

```
                 [cloud
I wandered lonely as a 
```

includes a parenthesis signifying the wrap-up, but when indexed, we would want to be able to search for and find the phrase "lonely as a cloud". (The overline position is achieved with CSS.)

At the moment we have no mechanism for specifying that specific elements should be entirely eclipsed prior to indexing. It would be nice to be able to do this:

```
<span class="ignore">[</span>cloud
```
and specify in the index configuration something like this:

```
<exclude type="ignore" match="span[@class='ignore']"/>
```
so that such elements would be purged from the file before tokenization happens.

**Comment by joeytakeda** [comment]
We do have that, don't we? Wouldn't:

```
<rule weight="0" match="span[@class='ignore']"/>
```

do precisely want you want?

**Comment by martindholmes** [comment]
Ah, you're right, it does. I got my match attribute wrong in testing. :-)
