### ISSUE TITLE
Add "How Do I..." section

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#75]
As discussed over email, we should have a "How Do I..." section of the documentation that that outlines some common things people want to be able to do (like ignoring inline text), but that can get buried in the documentation.

Some initial suggestions here, but we should use this ticket to compile more:

* How do I get staticSearch to ignore large chunks of my document?
* How do I get staticSearch to ignore small inline bits and still have them in the KWIC?
* How do I get staticSearch to ignore small inline bits and NOT have them in the KWIC?
* How can I get staticSearch to show debugging messages?

**Comment by martindholmes** [comment]
I think we can close this now; the section is there, to be added to when required, and I just tweaked the CSS to make the table a bit more readable.
