### ISSUE TITLE
Linux subsystems for Windows and forbidden filenames

### ISSUE THREAD

**Issue by lyallg** [projectEndings/staticSearch#77]
Hi guys.

I successfully built a search yesterday on Windows using Linux subsystems. One issue though is the inadvertent creation of forbidden (or reserved) windows filenames. In my case it is the creation of "con.json". So I can't copy, move, or delete this file. (I did delete one in the spring with some difficulty). 

List of reserved windows filenames:

CON, PRN, AUX, NUL 
COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

I am not sure if a workaround for windows users is worth your time considering I need Linux still to actually run the build, but I share for your info.

Other than this subsystems is a good solution for Windows users using your tool. Thanks.

**Comment by joeytakeda** [comment]
Thanks, Gord.

One solution might be to add con, prn, aux, and nul to your stopwords file. That would skip indexing "con" entirely, but that would mean users wouldn't be able to search for it.

**Comment by martindholmes** [comment]
Thanks @lyallg. I don't think there's anything we can do about that; if the word "con" appears in your documents, you're going to get a file by that name. You could add "con" to the stopwords list to prevent it being indexed, though.

**Comment by martindholmes** [comment]
I'm closing this after making it part of issue #33.
