### ISSUE TITLE
Creating rules and excludes?

### ISSUE THREAD

**Issue by lyallg** [projectEndings/staticSearch#80]
Sorry guys, hopefully this is my last one. I am really close. Thanks for the tip on adding troublesome Windows words to stopwords. I  commented out rules and excludes because they were breaking the build, but I do want to exclude headers, footers, and popups, for now, maybe more later. I added:
```
   <rules>
     
        <rule weight="0" match="header | footer | div[@class='popup']"/>
    </rules>
```

```
Error:
 [java] Create delete rules
     [java] <xsl:template xmlns:xsl="http://www.w3.org/1999/XSL/Transform" match="" priority="1" mode="clean"><xsl:if xmlns:xsl="http://www.w3.org/1999/XSL/Transform" test="$verbose"><xsl:message xmlns:xsl="http://www.w3.org/1999/XSL/Transform">Template #clean: Deleting <xsl:value-of xmlns:xsl="http://www.w3.org/1999/XSL/Transform" select="local-name(.)"/></xsl:message></xsl:if></xsl:template>

tokenize:
     [echo] Creating tokenized XHTML files...
     [java] Error at char 0 in xsl:template/@match on line 100 column 53 of config.xsl:
     [java]   XTSE0340  The expression is empty
     [java] Errors were reported during stylesheet compilation

BUILD FAILED
/mnt/d/Stuff/Bizness/MMRC/build.xml:187: The following error occurred while executing this line:
/mnt/d/Stuff/Bizness/MMRC/staticSearch/build.xml:182: Java returned: 2
```

I can see that in config.xsl there are empty values in @match, which is creating the error. But I am not sure why my <rules> is creating the issue. I imagine the match should look like 

`<xsl:template match="header | footer | div[@class='popup']" priority="1" mode="clean"> `

instead of 

`<xsl:template match="" priority="1" mode="clean">`

**Comment by martindholmes** [comment]
@lyallg Is there any way for us to see your site pages and config? If this is the bctextbooks project, I checked it out and tried to build it but I got a missing file error for  bctextbooks/trunk/xsl/../xml/chronologies/BCtextbooksChronology.xml (No such file or directory).

**Comment by lyallg** [comment]
@martindholmes this one is for a new project that I am designing for Hstr 324c. I am calling it MMRC (Mckenna-McBride Royal Commission). I am happy to share whatever you need to see but it is not on SVN. I would have to find another way. I could email config file and a sample html file?

**Comment by martindholmes** [comment]
@lyallg Do you want an svn repo for it?

**Comment by lyallg** [comment]
I changed rules to:
` <rules>
     
        <rule weight="0" xpath="header | footer | div[@class='popup']"/>
    </rules>`

And it is running now. But it is my understanding it should be @match and not @xpath ?

**Comment by martindholmes** [comment]
@lyallg Let's take the rest of this discussion offline, since it doesn't relate to the issue you've raised.

**Comment by martindholmes** [comment]
@lyallg Did this get solved? If so, can you close the ticket?
