### ISSUE TITLE
Eliminate upper-case index

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#85]
Following a discussion on issue #60, we think a better option for handling name-searching is to base it on the keyword-in-context system. The most straightforward approach would be for the JS to assume that any token beginning with an upper-case letter should be searched as though it were a quoted string, but we don't actually distinguish case when doing phrasal searches -- e.g. http://johnkeats.uvic.ca/search.html?q=%22expressed%20by%20hazlitt%22. So we need to think a little about how best to accomplish this. Do we treat unquoted tokens beginning with upper-case letters as distinct, case-sensitive "phrasal" searches?

**Comment by martindholmes** [comment]
@joeytakeda I was thinking of punting this to 1.2 because I don't think we're clear on exactly how it should work and what the implications are yet, but having dug around a bit I think it might be a really good contribution to 1.1 and make it well worth the upgrade. It would be great to get rid of the upper-case index, and actually it's not clear to me that we're making much use of that index anyway; searching for `black`, `Black`, `"black"` and `"Black"` on Keats retrieves exactly the same set of results, so I suspect our original intended use for the upper-case index was never properly implemented. So it's possible we could simply remove it right now, and speed up the indexing, speed up the JS search, and reduce the index size without any penalty. What do you think?

**Comment by joeytakeda** [comment]
Strange that “Black” and black return the same results since the exact phrase was case sensitive, I thought. If it’s not, then we should make sure it is, and then I think we can eliminate the uppercase index. 

It would increase the XSLT speed quite a bit, I think, since we wouldn’t need to check for words being in the dictionary. We may still want that as a feature (it is helpful in the diagnostics for instance), but I think the uppercase thing is the only time we actually do anything with the results of dictionary checking.

**Comment by martindholmes** [comment]
This line in the JavaScript make phrasal searching case-insensitive:

~~~~~
  //Make the phrase into a regex for matching.
            let rePhr = new RegExp('\\b' + rePhrStr + '\\b', 'i');
~~~~~

due to the "i". That's been there since the beginning, so we've never been trying to match phrases case-sensitively. I'm not sure if we should be. If we make phrasal matching case-sensitive, we can absolutely use it to search for names, by treating any upper-case term entered into the search box as a phrasal search. I think the reason we're not using the upper-case index well or properly is based in the fact that we search both upper- and lower-case indexes for any capitalized term, and because lower-case indexes also include lower-cased versions of all upper-case terms, the net result is the same set of matches. That clearly needs rethinking. If we discard the upper-case index at this point, I don't think anything will change (easy enough to test in a branch); but we can't remedy the case problem by switching to treating upper-case terms as phrases as things stand, because we're not treating phrases case-sensitively.
The options as I see them are:
1. Drop the upper-case index and leave phrasal searching alone. Result: no name-optimized method of searching, but smaller indexes and faster build times and searches.
2. Drop the upper-case index, make phrasal searching case-sensitive, and treat upper-case single words as phrasal searches. Result: fewer hits from phrasal searches -- some searches that currently succeed will fail -- but a reliable way to search for upper-case terms (which will help with names and proper nouns); smaller indexes and possibly faster searching (more complex query parsing, but fewer JSON files to retrieve).
3. Something else?

**Comment by martindholmes** [comment]
Any reason not to close this now?

**Comment by joeytakeda** [comment]
Should be good to close--I'll do that.
