### ISSUE TITLE
Multiple filter searches returning too many results

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#9]
The expected behaviour of searching across filters is that, within a particular filter, the user will receive documents that match ANY of those filters; across filters, the user should receive documents that match ALL of the filters.

Currently the JS is returning ANY both within and across filters; for instance, searching for

Document Types: Novels
and
Pseudonym: Onoto Watanna

Returns all items that have the pseudonym Onoto Watanna OR is a novel.

**Comment by martindholmes** [comment]
I believe this was fixed in the last merge from dev.
