### ISSUE TITLE
Harmonize/clean up filter creation in tokenize.xsl and json.xsl

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#92]
We currently do the assignment of filter ids in tokenize.xsl using a series of variables and maps:

```xsl
 <xd:doc>
        <xd:desc>Map of all of the descriptive filters found in the *entire* document
        collection. This is necessary so that each descriptive filter gets a unique id.</xd:desc>
    </xd:doc>  
    <xsl:variable name="descFilterMap" as="map(xs:string,xs:string)">
        <xsl:map>
            <xsl:for-each-group select="$docs//meta[contains-token(@class,'staticSearch.desc')]" group-by="@name">
                <xsl:map-entry key="xs:string(current-grouping-key())" select="'ssDesc' || position()"/>
            </xsl:for-each-group>
        </xsl:map>
    </xsl:variable>
    
    <xsl:variable name="dateFilterMap" as="map(xs:string,xs:string)">
        <xsl:map>
            <xsl:for-each-group select="$docs//meta[contains-token(@class,'staticSearch.date')]" group-by="@name">
                <xsl:map-entry key="xs:string(current-grouping-key())" select="'ssDate' || position()"/>
            </xsl:for-each-group>
        </xsl:map>
    </xsl:variable>
<!--+++ Etcetera +++ -->
```

But that's redundant, since we re-group these things in json.xsl to create the filters (`$thisId`) : [1]

```xsl
<xsl:for-each-group select="$tokenizedDocs//meta[matches(@class,'^|\s+staticSearch\.')][not(@data-staticSearch-exclude)][not(ancestor::html[@data-staticSearch-exclude])]" group-by="tokenize(@class,'\s+')[matches(.,'^staticSearch\.')]">
            
            <xsl:variable name="thisClass" select="current-grouping-key()"/>
            <xsl:variable name="metaNum" select="position()"/>
            <xsl:for-each-group select="current-group()" group-by="@name">
                <xsl:variable name="thisName" select="current-grouping-key()"/>
                <xsl:variable name="thisId" select="current-group()[1]/@data-staticSearch-filter-id"/>
<!-- and so on -->
```

But the same could be achieved by simply getting the position of the filter in the second `<xsl:for-each-group>`, since that's grouping the filters by name already. And the search page creation gets the filter ids and values from the JSON files anyway, so there's no real reason that we need to do that work in `tokenize.xsl` as far as I can tell. In any case, we do all of the rest of the complicated work on the filters in `json.xsl`, so it's probably better to keep that all in one place.

<hr/>

[1] Plus, it's inefficient / memory intensive according to the  Saxon's collection spec: https://www.saxonica.com/documentation/#!sourcedocs/collections as it requires all of the meta tags to be loaded into memory and sorted.

**Comment by martindholmes** [comment]
Absolutely agree.

**Comment by martindholmes** [comment]
@joeytakeda Is this done? If the code is done and it's just inline commentary/documentation that's required, we could kick that to 1.2.

**Comment by joeytakeda** [comment]
Yes, code is done but the PR isn’t merged and now is going to be out of date with potential merge issues. Let’s kick this to 1.2, and I’ll deal with the merge issues after that.

**Comment by martindholmes** [comment]
@joeytakeda Where does this one stand now? I don't see a PR, so either it got merged or nuked.

**Comment by joeytakeda** [comment]
Or woefully neglected by me :-). There is a branch for it, but it's now completely out-of-date: https://github.com/projectEndings/staticSearch/tree/issue-92-cleanUpMeta.

I'll work on this tonight. Rather than have the royal pain of trying to merge the files in, I'll just start this again in a new branch using the old branch as an informal guide for how to proceed. That'll be more work, but so be it (and it's a good reminder for me not to finish things I start!).

**Comment by joeytakeda** [comment]
Okay, so I've now created a new branch (sigh) called 2021-issue-92-cleanUpMeta with the changes in place. Tried it with the test set and all is well, but I'm going to switch LOI to this to make sure I haven't broken anything.

**Comment by martindholmes** [comment]
Looks like LOI built successfully, but I'll leave it to you to check the results and create a PR. Sorry you had to do this twice.

**Comment by martindholmes** [comment]
Judging by the LOI build on Jenkins and my quick local tests, this shaves the build time noticeably.

**Comment by joeytakeda** [comment]
The LOI one is a bit of an exaggeration since there was a bit of a stau in Jenkins where all of of the Big Projects, but on my local build of LOI, it took off about 10-15 minutes.

I think should be good to merge now; I've done a PR and we can watch to make sure the rest of the projects work properly.
