### ISSUE TITLE
Need better handling for word-internal apostrophes

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#95]
The XSLT and Javascript handle word-internal apostrophes differently: the XSLT tokenizer understands apostrophes as word separating, so something like `O'Doyle` is understood as two tokens: `O` and `Doyle` while the Javascript removes all apostrophes from the input (so `O'Doyle` becomes `ODoyle`). These should be aligned.

The XSLT tokenizing step is fairly straightforward:

* Add all apostrophes to the token regex, so that `you'll`, `O'Leary`, and `cactus’` are all considered a single token
* In the cleanWordForStemming function, we remove the single apostrophes (curly or straight) from the beginning and end of a string, but retain any word-internal ones, but convert them to straight apostrophes for the purposes of stemming `you'll`, `O'Leary`, `cactus`

But I'm not sure what ought to be passed to the stemming process:  should `O'Leary` be stemmed twice (as `OLeary` and `O'Leary`) or should that internal apostrophe be elided and thus the token to stem is `OLeary` (as per the JS)?

**Comment by martindholmes** [comment]
For the stemming, I think this is a good argument for retaining the upper-case versus lower-case distinction. Any name needs to retain its apostrophe and not be stemmed (at least, an unstemmed version should be available to the search). Any common contraction with an internal apostrophe (you'll) should probably be in the stoplist anyway; and for the possessives of common nouns, we can check what Porter does with them for English.

**Comment by joeytakeda** [comment]
Porter has quite a bit to say about apostrophes in English:

http://snowball.tartarus.org/texts/apostrophe.html

Which basically confirms our plan: the apostrophe should be removed from the beginning and end of the word, common contractions should be understood as stopwords, and in all other cases preserve the apostrophe—R0 handles possessives and the like. 

So beyond the changes to the XSLT so that apostrophes are not considered word separating (and should be normalized to straight), the only other change that needs to happen is that the JavaScript shouldn’t strip internal apostrophes.

**Comment by martindholmes** [comment]
I think the intention is to normalize them to straight apostrophes only at the stemming stage; in other words, it should happen in the two Porter 2 stemmers, not at the tokenization stage. That enables us to preserve the precise form in the KWIC. Is that what's happening now?
I'll take a look at the stemmers and see what's happening there; it's easy to add apostrophe-normalization to the pre-flight stuff (where IMHO we ought also to add long-s to s conversion).

**Comment by joeytakeda** [comment]
Yes that normalization happens after the text has been tokenized but before it gets passed through the stemmer in the cleanWordForStemming function.

**Comment by joeytakeda** [comment]
Started a branch for this. I've added a re-encoded version of Porter's apostrophe document to the repository, since it includes all sorts of examples (plus it's "Worth Reading" so might as well add it) that are helpful for testing purposes.

**Comment by martindholmes** [comment]
Good call. Do the licence terms on his doc allow us to use it?

**Comment by joeytakeda** [comment]
As far as I can tell: https://snowballstem.org/license.html

The text isn't software, but there's no other license specified on it (this is the same version on their newer website: https://snowballstem.org/texts/apostrophe.html). In any case, I've now just taken a segment of the document and encoded it as a `<blockquote>`: https://github.com/projectEndings/staticSearch/blob/2f7ee3d57210c7ba6074f0b496fcbca96b18dec0/test/apostrophes.html

**Comment by joeytakeda** [comment]
This should now be basically done. I did have to make a small adjustment to phrasal search, since it was sensitive to the type of apostrophe uses (curly vs straight). I added two instances of o'clock to the apostrophes document; the first has a straight apostrophe and the second has curly (from the Porter quotation). When you do a MAY CONTAIN search for `o'clock` you get back (bold here to denote the `<mark>`):

> ...it provides good examples of apostrophes (for instance, **o'clock**, O'Reilly, etc.).↬
> ...what is now accepted as a single word: **o’clock**, O’Reilly, M’Coy. Except in proper names such...↬

A search for `"o'clock"` however only returns the first one, since the second has a curly apostrophe and does not match. I didn't think that should matter, so I've now changed the phrasal search (in commit aa9c7fe471143180e201a36b325246204adf294b) such that it expands any single apostrophe to a character class:

```
  //Expand apostrophes into their variants
           let rePhrStr = self.terms[phr].str.replace(/'/g, "['‘’‛]");
  //Make the phrase into a regex for matching.
            let rePhr = new RegExp('\\b' + rePhrStr + '\\b', 'i');
 ```

**Comment by joeytakeda** [comment]
[@martindholmes I'm moving your comment on the commit here just to keep everything in the same thread.]

> I'm really not sure about this; it seems to be going a bit backward. A phrasal search should make it possible for anyone to search for exactly what they're looking for -- including straight or curly apostrophes. If they want to search for both, they can make their own wildcard surely? If they're not using phrasal search, then the stemmer should take care of this equivalence, no? (https://github.com/projectEndings/staticSearch/commit/aa9c7fe471143180e201a36b325246204adf294b#commitcomment-45257500)

Wildcards don't work in phrasal searches, so they can't use a wildcard for that. And no, the stemmer itself does not handle the differences between curly and straight apostrophes, but all of our pre-processes do (as per Porter's instructions that "other codes for apostrophe can be mapped to this code [U+0027] prior to stemming").

Re: making it possible to search for exactly what you want--I've opened a ticket #98 about other punctuation, since apostrophes are the only thing that are actually retained in phrasal searches. But in terms of the apostrophes, I can't think of an instance where there's any use case (beyond investigating the use of straight and curly apostrophes, I guess) where that difference matters. And I don't think it will clear to the average user that a search for something--like "Paul's Churchyard"— returns no results because of a difference in curly/straight apostrophe (especially since it's not easy to input a curly apostrophe instead of a straight one).

**Comment by martindholmes** [comment]
What worries me is that we're baking language-specific stuff into generic code. I know the JS is already partly doing that, but it's mainly because some glyphs are control characters for the search string.

Let's think it terms of desired behaviours:

 - For stemmed tokens, we want to strip all punctuation except apostrophes, and we can normalize apostrophes before stemming.
 - For returned KWICs, we should preserve exactly what is in the original including punctuation and apostrophes, curly or straight, because that enables the searcher to see the difference if it matters to them, and it gives the scroll-to-text-fragment better chance of success. 
 - For phrasal searches, we should expand apostrophes to wildcards when doing the matching against the KWIC because the KWIC may contain either variant. This behaviour is worryingly specific to English, but it will also extend to French, and perhaps most other European languages; where curly apostrophes are glottal stops, though, in contrast with straight apostrophes as punctuation (for instance), it may introduce some complications. 
 - For projects which lack a stemmer and thus depend on wildcards, we have to hope that the behaviour we've baked in will not introduce errors. But we can't really predict that without real-world examples.

Is that a fair summary?

**Comment by joeytakeda** [comment]
Yes, that's a fair summary and your point about this being language specific is absolutely right. I completely agree that we need to disambiguate the language-specific processes from generic ones, but that's really a much bigger project and one beyond the scope of this issue. #70 provides a start for this, but really we need to do a full audit of staticSearch, determine what is language specific and what is generic, and then hive off language specific things into their own module (following the example of the stemmer, I think).

For the purposes of this ticket, I think the apostrophe handling is okay since it works correctly for English and the code already has some baked in language-specific assumptions, which should be fixed in a concerted campaign once we've come up with a good plan for handling other languages. How does that sound to you?

**Comment by martindholmes** [comment]
Sounds good. I think we're off to a good start with the way the stemmers are working, and I think the tokenizer approach we have now will work for most languages we're likely to be able to write a stemmer for.

**Comment by joeytakeda** [comment]
How should we proceed with this? Since we need to figure out exact phrase punctuation in any case (#98), I'm happy to roll back (or comment out) the apostrophe expansion stuff per: https://github.com/projectEndings/staticSearch/commit/aa9c7fe471143180e201a36b325246204adf294b (or comment out) and then handle all punctuation in exact phrases in #98.

Does that seem good to you?

**Comment by martindholmes** [comment]
I really don't know. I go back and forth between thinking that we should let people search for exactly what they want to find, and thinking that most people will be confused by not finding curly apostrophes when they searched for straight ones. My summary says "we should expand apostrophes to wildcards when doing the matching against the KWIC", and that's what your commit does. My comment on #98 seems to be pointing at an irrelevant line of JS, so I don't know what I was thinking there, unless subsequent changes have just shifted the source around. 

I don't think we should be stripping out punctuation from phrasal searches, though; that means that a straight copy-paste from a source document will not find a hit if it's quoted and it has an apostrophe in it. So that definitely needs fixing. Apostrophe expansion seems a reasonable thing, since it won't eliminate any hits, and it should work out of the box, given that we test the match as though it's a regex (`if (rePhr.test(unmarkedContext))`) and the wildcard will work as a regex component as-is.

**Comment by joeytakeda** [comment]
Yes, I think we should expand apostrophes to wildcards, too, but my main thing is whether that's a job for _this_ ticket (i.e. should this be part of the apostrophe handling) or if this be done in a concerted effort with the rest of #98. 

My thinking here is that regardless of whatever default behaviour we settle on—and my vote is for the normalization of apostrophes but not much else—we should make that normalization process a function so that it can be overridden if necessary--that way, if some project does care about the curly quotation marks, for instance, it's easy to implement (and, going the other way, this would allow projects to do other mappings in exact phrase searching--like long-S to regular--which isn't totally obscene, since that is what ctrl+f does in Chrome at least).

That said, I'm happy to keep that commit so that the logic is still there--we can change it when we address #98 anyway.

(And for your comment on #98, I think you were just off a few lines:

https://github.com/projectEndings/staticSearch/blob/4e146ac28399b4a844d5f86e10271ec0cb800e30/js/ssSearch.js#L661-L677

Those line embeds are pinned to commits so they shouldn't ever shift)

**Comment by martindholmes** [comment]
Ah yes, I meant starting from that line. If we were to remove lines 666 and 667, what would happen? It would mean that you wouldn't get a phrasal search if you had used curly quotes, but is that a disaster?

**Comment by joeytakeda** [comment]
Removing 666 would do as you said, I think, which I don’t think is disastrous. 

Removing 667 (which is newly added for this issue) would mean we’d have to do the apostrophe normalization elsewhere, since word internal apostrophes are straightened for the token files and so we need them to be normalized for the stemmed searches.

I’m going to do a PR for the apostrophe branch now, since that branch addresses the problem of word-internal apostrophes; once that’s merged, I think we should move the punctuation normalization stuff to its own branch for the #98.

**Comment by martindholmes** [comment]
The 95 branch is 4 commits behind dev; can you merge dev into it and test again before we merge the pull request? I'm not sure we don't have some conflicting commits here.
