### ISSUE TITLE
We should not insist on fixed order for params in config schema

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#97]
Our ODD file specifies the content model of the `<params>` element using (correctly) `<sequence preserveOrder="false">`, which should allow the specified number of each child element (one, optional or mandatory, in all cases) to be in any order at all. However, the TEI Stylesheets fail to process this correctly (see [this](https://github.com/TEIC/Stylesheets/issues/241) and [this](https://github.com/TEIC/TEI/issues/1970), so we have the annoying situation where config files can easily be "invalid" just by getting them out of order.

I propose a solution to this: if we simply preprocess the ODD file at build time to replace `<sequence preserveOrder="false">` with `<rng:interleave>`, the result will be correctly processed into the right content model in the resulting schema. The intermediate schema is technically invalid, but that doesn't matter because nobody will see it.

I'm going to create a branch for this and implement it, because I keep creating accidentally-invalid config files, and it's driving me nuts.

**Comment by joeytakeda** [comment]
Yes, absolutely agree--I was just thinking about how annoying this is the other day when I added the config option, so thanks for fixing this.

**Comment by martindholmes** [comment]
This seems to be working, so closing.
